### ISSUE TITLE
Making "cash yields" more interesting and meaningful

### ISSUE THREAD

**Issue by devolution79** [We-the-People-civ4col-mod/Mod#337] opened 2019-12-30 08:52 UTC
WTP has a large number of diverse yields that are not very interesting by themselves since they are usually just shipped off to Europe to be sold for cash. What if we instead integrated them into the game in more coherent and interesting manner:

Salt, spices, coffee, cacao, etc could boost health when consumed by the market. 

We could introduce a happiness mechanic that would use the alcoholic yields (rum, beer, wine) and "drugs" like coca\cigars (and maybe hemp)  to generate happiness that would make it harder for large cities to stay productive unless they have ample supplies of these. The tavern line should then be re purposed for happiness purposes.

Not entirely sure about clothing yields like coats(both types), wool, leather and cloth , but I'm sure those could be integrated as either health or happiness boosters as well. 

Advanced buildings like the Government Palace and the Opera should require furniture.

The Health\happiness quota should be per yield type to reward diversity.

Another thought on uses for yields: What about a "yield upgrade" mechanic where units could be granted promotions for consuming a yield. Ships could gain additional movement from salt (food conservation) or morale from rum (all sailors need rum!) , soldiers could get fur coats that grant bonuses in tundra\arctic conditions. Whale oil could make cities more productive (whale oil was mostly used for candles\lighting) etc.

**Comment by ErikSandbraaten** [comment] 2019-12-30 09:53
https://github.com/We-the-People-civ4col-mod/Mod/issues/317

**Comment by ErikSandbraaten** [comment] 2019-12-30 09:55
#317

**Comment by Drunk-Monk** [comment] 2019-12-30 10:43
Good ideas, although I disagree about the unit bonus as the game doesn't really feature logistics on that scale. As to your other points, I have raised the same issues here:  #296 #317 #312 I have also modded my xml to reflect these ideas, which I will send to you.

**Comment by NoFreeUsernameDammit** [comment] 2020-01-02 13:44
I've got a half-baked idea that's rather different, but could be interesting. Trading posts.

Right now, the trading with natives is rather limited, since the natives are just passive receptors for bulk loads once in a while. This would allow a bit more long term trade with them.
You establish a trading post using pioneers in close proximity to native settlement. As long as the settlement stands, you could ferry some specific goods to it, and the goods would be gradually sold for gold and raw materials gathered by natives.
Now the problem is I'm not well versed in what the game engine allows in this regard, whether the goods can be stored in a tile improvement, how would demand and price be determined, and the automation of such trade.

**Comment by dcrookston** [comment] 2020-01-02 22:59
Re: trading posts

I think everyone should give the Dawn of a New Era a quick playthrough. He
implements a lot of really cool things that would (IMHO, obviously) be
great additions to WTP.

One of these is trade agreements with the natives. You can agree to trade X
of their goods for Y of our goods over 15 turns. The wagon that was there
when you made the deal is auto-assigned to that trade route, and it brings
a small amount of goods back and forth each trip.

After 15 turns, if you have fulfilled your side of the deal, you get a
little bit of trust from the natives and you can make bigger and longer
term deals. If you complete a couple of these deals, you get a +1 to
reputation with them for fair trading.

One thing I like about this is that you can't trade money with the natives.
They will only trade for goods -- tools, trade goods, and pretty much any
manufactured good.

**Comment by LibSpit** [comment] 2020-01-03 02:32
In medieval Conquest a lot of yields were consumed to produce abstract yields like law and culture, these yields were then used to create immigration and border expansion. A lot of the clothing/armour yields were used to create better units or even units with starting promotions. Chainmail or plate armour promotions, knights requiring plate and chain, bowman requiring leather armour, etc.

so two types of cloth could be used to build cavalry for example (representing a fancier uniform for these elite gentlemen soldiers.

Spices could be consumed by cathedrals to increase cross production or other production boosting properties for the more 'abstract' yields. luxury items could be consumed to produce liberty bells for example.

**Comment by raystuttgart** [comment] 2022-11-27 18:07
This post is completely outdated.
Too much considering Yields has happend in the current release.

So let us please close this.
If necessary, we can start a fresh discussion.

Discussing based on 2.7 or something will not help.
(Since we are soon going to publish 4.0)

**Closed by raystuttgart** 2022-11-27 18:07 UTC
Labels: enhancement, IDEA, Discussion
