### ISSUE TITLE
Founding fathers avoiding me

### ISSUE THREAD

**Issue by andushow** [We-the-People-civ4col-mod/Mod#982] opened 2024-01-20 20:20 UTC
Context:
All political/military/religion/etc. points maxed out; all FF assigned to a nation or another.
Having defeated the Danish, their FF became available again.
I was expecting next turn to be offered one of them, however the French got one, some more are free without me having any chance of claiming them. 
Any idea why ?
[George Washington AD-1697-May.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13999140/George.Washington.AD-1697-May.zip)

**Comment by Razonatair** [comment] 2024-01-21 00:33
I can confirm this save does have the issue explained in the opening post in 4.1. Perhaps the logic for getting newly available Founding Fathers doesn't actually work, I'll take a look at the code, but someone else might want to as well.

**Comment by Razonatair** [comment] 2024-01-21 00:51
So I tested this save with my new FF logic, and it works perfectly fine. There's some issue specific to 4.1.

**Comment by Razonatair** [comment] 2024-01-21 00:58
I can't identify exactly what the problem is in 4.1, but the new logic I've designed works flawlessly for this save. So, if the logic is accepted for the next release, this bug will be fixed then naturally.

**Comment by MrZorG33** [comment] 2024-01-22 05:30
@Razonatair I was able to take all the unclaimed FFs in one turn. this needs to be fixed. you need to make sure that in one turn you can take only one FF (but at the same time leave a choice from the available ones).

**Comment by Razonatair** [comment] 2024-01-22 05:36
I disagree, that wasn't the point of the new logic, the point of the new logic is returning to have an unlimited number of FFs be offered per turn. This particular save is able to take all the unclaimed FFs simply due to be ridiculously powerful with an AI that is basically nonexistent.

**Comment by Razonatair** [comment] 2024-01-22 05:37
If you intend to have the newly available FFs be a separate class of FF, I would need to rework how they're made available and how they're flagged in order to have separate logic apply to them.

**Comment by MrZorG33** [comment] 2024-01-22 05:45
let's continue in the work chat.

**Comment by Razonatair** [comment] 2024-01-22 15:17
This issue will be resolved in the next release which will include the new Founding Father Competition code.

**Closed as completed by Razonatair** 2024-01-22 15:17 UTC
