### ISSUE TITLE
Spiel stürzt ab nach "End of turn" im Jahr 1590 AD

### ISSUE THREAD

**Issue by Geherd** [We-the-People-civ4col-mod/Mod#581] opened 2022-03-06 10:53 UTC
Grüß Euch,

mit Begeisterung spiele ich Eure Mod WTP - leider stürze ich jetzt immer an der selben Stelle ab!
Im Jahr 1590 AD, beim Drücken auf "End of turn" ist jedesmal Schluss!
Egal ob ich direkt bei meinem SaveGame von diesem Jahr einsteige oder etwas früher starte und problemlos bis ins Jahr 1590 AD spiele.
Dort ist dann Schluss :-(

Nachdem ich ansonsten problemlos spielen kann, schätze ich, dass ich alles richtig installiert habe.

2 meiner SaveGames:

[Samuel de Champlain AD-1590.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8192391/Samuel.de.Champlain.AD-1590.zip)

Danke für Eure Unterstützung!

**Comment by Taunaic** [comment] 2022-04-23 10:00
Join :( The same issue, but in different (mid/end) turns in many scenarios/speeds. Just throws from game, after "End Turn" to the desktop without any errors. Steam version (original release unsupported).
[Dutch Colony AD-1696-May.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8546634/Dutch.Colony.AD-1696-May.zip)
 What we do wrong?(((

**Comment by raystuttgart** [comment] 2022-04-23 10:19
Hi guys, please let us know the **version** you play.
Do you guys play the last public release **3.0.1** ?

**By the way:**
A lot of bugs in 3.0.1 have **already been fixed** internally.
(Chances are really high that your bugs are already fixed as well.)

**Comment by Taunaic** [comment] 2022-04-23 10:46
> 
Hi, great modder!)  As for me, i play on the last public release 3.0.1. 
Interesting moment...Yestarday, when i wont to "join" to this thread, go to save location, run the game, to be sure, that this save is wright before "error/issue"... push "end turn" and no bad happened (I try many scenarios/new game, load and load last normal turn and push with hope "end turn" many maaaany times before - always the same), but yesterday its work properly.  Happy, i play all nignt.. but after some 10+ turns, againe "end turn and throws to a desktop".

**Comment by raystuttgart** [comment] 2022-04-23 10:57
**@Taunaic** 
Thanks for telling the release version. 👍 

As I said, release **3.0.1** is already **more than 9 months old** ... it is completely outdated.
We **simply have not yet released** all the stuff we have fixed and implemented since then.

**Summary:**
Simply have a bit of patience until we finally publish all the bugfixes that we already have.
(More or less all bugs we have been reported in the last 6 months are interally already fixed.)

**Comment by Geherd** [comment] 2022-04-23 18:24
Hello,
I guess I'm also playing 3.0.1 since my Mod-Folder is **"My Games\Civilization IV Colonization\MODS\WeThePeople-3.0.1"**.

Thanks for the info and I'm looking forward for the next release - big thanks for your work!
(in the meantime i started all over with the english (William Penn) and no crashes so far :)

**Comment by devolution79** [comment] 2022-07-13 09:59
I suspect that this is another duplicate of the divide by zero issue that's been reported a half-dozen or so times

**Closed by devolution79** 2022-07-13 09:59 UTC
