### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by pedro-walter** [We-the-People-civ4col-mod/Mod#465] opened 2021-05-23 03:35 UTC
Hi folks,

As always, I need to first thank you guys for creating this wonderful mod which keeps me glued to playing this game even after so many years.

Got a random crash happening, not sure if it's a mod problem or a game problem. I made a video explaining the steps to reproduce it:

https://youtu.be/4zonE1wElHQ

And I'm attaching the savegame file, you can also find it here:

https://drive.google.com/file/d/1nWsRsq7T2c5el73sB3Bfg8Lf7prALp8c/view
[AutoSave_AD-1534.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6527483/AutoSave_AD-1534.zip)

**Comment by pedro-walter** [comment] 2021-05-23 03:43
For some reason, I tried a few different combination of the commands I've posted in the video without anything triggering the crash, and now when I tried reproducing the error exactly as in the video, it works without a problem. Maybe creating an extra autosave file in the following year, then loading the game kinda fixed the issue, I'm lost :(

**Comment by Nightinggale** [comment] 2021-05-23 09:29
I can confirm that it is crashing. It's related to the barbarian player testing CvPlayerAI::AI_professionValue testing UNITAI_DEFENSIVE for PROFESSION_COLONIST. It wants to look up date from getDefaultProfession(), which then crashes because it's NO_PROFESSION.

Looks like a revolting criminal captures La Isabella and then the AI gets confused because the barbarian player lacks settings to run a colony.

**Comment by Nightinggale** [comment] 2021-05-23 11:49
I got it to not crash meaning I have found the offending code. Now I just have to fix it in a way, which won't be prone to break in the future.

**Comment by pedro-walter** [comment] 2021-05-23 12:45
Glad it was useful!

**Comment by Nightinggale** [comment] 2021-05-25 17:45
Fixed in 08052d73e84a771866c5f0cb52691b5edea6f41b
(yes I just noticed the issue number typo... too late to change that now)

**Closed by Nightinggale** 2021-05-25 17:45 UTC
Labels: bug
