### ISSUE TITLE
Production/Yields Stalled

### ISSUE THREAD

**Issue by simplywog** [We-the-People-civ4col-mod/Mod#678] opened 2022-12-23 21:38 UTC
My production of cocoa, wine and fur are stalled in my initial colony and not sure why. It indicates I should be producing positive yields with each turn, my storage capacity is only at 20% and my citizens are happy. Not sure what would cause this or if just a bug? Using 3.0.1. I am quite new to WTP.

**Comment by raystuttgart** [comment] 2022-12-23 21:44
It is possible that the Yields are sold through Domestic Market.
It is a very common thing that players get confused because although it gives +X in green at end turn there is no additon.
Please check the Domestic demand.

By the way:
From such a "poor description" it is almost impossible to really say what the problem is.
Please at least provide a screenshot. ;)

**Comment by Nightinggale** [comment] 2022-12-23 21:46
> Please at least provide a screenshot if you really expect an analysis and help. ;)

A savegame can also help when trying to figure out what is going on, particularly in a case like this one where it's proposed that the internal calculations results in some incorrect result.

**Comment by simplywog** [comment] 2022-12-23 22:12
![BE3DA92B-2869-4DC2-9E79-20E4DEC351E8](https://user-images.githubusercontent.com/121318578/209409333-b216a4ab-0349-4778-b3a5-da1b379e5d48.jpeg)

Hopefully the photo attachment works.
The cocoa, coats and silver have been stalled at those amounts for about 8 or 9 (I think) turns. The guns, cannons, blades etc. have continued to increase. Sorry, I’m not sure how to better describe this. Is there any other screenshot page I should upload?

Nightingale, I’m not sure what you mean with your “save game” comment?

**Comment by simplywog** [comment] 2022-12-23 22:23
![BAD11D10-9239-4386-B2B4-3CA58B3DA2D3](https://user-images.githubusercontent.com/121318578/209410245-9995df17-2dcd-4bf8-b9c2-53ea02db4f5a.jpeg)

**Comment by simplywog** [comment] 2022-12-23 22:57
> > Please at least provide a screenshot if you really expect an analysis and help. ;)
> 
> A savegame can also help when trying to figure out what is going on, particularly in a case like this one where it's proposed that the internal calculations results in some incorrect result.

Demand is zero for any of these items domestically.

**Comment by raystuttgart** [comment] 2022-12-24 07:54
Why did you not make normal Screenshots and made these ugly hard to check Photos instead?
(Screenshots can be made pressing "Print"-Key" - they will be stored in the folder "Screenshots" of Civ4Col.)

Please make normal Screenshot or even better attach a Savegame.
(Savegames are stored in the folder ""Saves".)

**Comment by raystuttgart** [comment] 2023-01-14 13:12
Since this is totally outdated with Version 3.0.1 we will close this.
Nothing like this was reported anyways ever and also not in Release 4.0

**Closed by raystuttgart** 2023-01-14 13:12 UTC
