### ISSUE TITLE
founding city crash

### ISSUE THREAD

**Issue by IFoundabugg** [We-the-People-civ4col-mod/Mod#801] opened 2023-04-08 23:00 UTC
[AutoSave_AD-1528.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11184395/AutoSave_AD-1528.zip)

Encountered on official 4.0 release.

Go straight to prepared settler, found city and select 'buy land' option. It crashes for me before or after accepting Plymouth as city name.

Make sure to deal with settler 1st. It doesn't appear to crash if you deal with other units first.

**Comment by IFoundabugg** [comment] 2023-04-08 23:07
Just to add I am selecting 'buy land' option.

Also to confirm, If you deal with other units first it doesn't crash for me.

**Comment by raystuttgart** [comment] 2023-04-09 05:26
Thanks for the Savegame.
That way it shoud be possible to analyze and fix.

**Comment by Nightinggale** [comment] 2023-04-09 09:28
I can reproduce the crash, through it seems strange. It is not consistent as I can do the same thing maybe 4 times without crashing and then I do precisely the same again and it crashes. Sadly the crash happens in the exe file, hence outside of our code meaning the debugger doesn't really tell us anything useful.

Considering that it happens in the exe, my guess is that it is related to graphics, through that alone is too vague to do anything about that.

I will put this on hold for now, implement #696 and that way gain access to log the calls from the exe. Knowing the last or last few calls might be able to tell us where to look for this crash.

**Comment by IFoundabugg** [comment] 2023-04-09 10:32
Do you suspect the crash is connected to it being fairewether map generation?

**Comment by Nightinggale** [comment] 2023-04-09 11:39
> Do you suspect the crash is connected to it being fairewether map generation?

That is unlikely. Regardless of what the map generation comes up with, the game itself should be able to handle it. The game shouldn't crash even if say the tropics have permafrost or whatever else a flawed map generator can come up with. Once the game has started, the map script is no longer active and as such shouldn't be able to cause issues at all.

The issue is more likely some tree, building, unit etc, which has flawed graphics in some way. The question is what it could be and how to figure it out. I mentioned implementing #696 and I will stick to that plan. Logging what the exe is doing seems to be the only way to figure out what is going on without resorting to randomly guessing.

**Comment by IFoundabugg** [comment] 2023-04-09 14:17
Sorry, To be honest #696 is way beyond my capability. Trying to head my head around it, but huge respect for what you are doing,

**Comment by raystuttgart** [comment] 2023-04-14 15:47
That bug is already fixed internally to my knowledge.
(It was the one with Effects if I am correct.)

**Closed as completed by raystuttgart** 2023-04-14 15:47 UTC
Labels: bug
