### ISSUE TITLE
Extra wIthdrawal probability is inactive for some units

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#974] opened 2024-01-10 10:22 UTC
Currently almost every naval unit has extra withdrawal probability of 10%.
This represents an extra chance to stay alive even if the battle is lost.
But according to the code extra withdrawal chance is activated only for the attacker.
And most trading ships can NEVER attack, thus for them extra withdrawal chance is useless.

My proposal is to keep things how they are now de facto,

I suggest only a minor correction: 
**Remove extra withdrawal chance for all units that cannot attack.**

**Comment by MrZorG33** [comment] 2024-01-10 10:43
why can't ships that can't attack have a chance to withdraw from a battle if they lose it?

**Comment by raystuttgart** [comment] 2024-01-10 11:13
Yes, if a Unit cannot attack, the withdrawal chance should be removed. 👍 
(As the code explicitly does not trigger withdrawal for it. - This is working as designed.)

**Explanation:**
Anything else would be very annoying to the player as Units you want to attack could simply run away again and again.
Players would really be pissed if during Combat a losing Unit would at the end just flee and you would have to chase it.

**Considering Immersion:**
Also "Withdrawal" (ending combat) and "Fleeing" (running away) are totally different things. In Military tactics only the stronger force can withdraw to prevent unnecessary loses. A weaker force fleeing during battle usually results in total chaos and obliteration by the stronger force.

**Comment:**
The other thing is **evasion**, which is a different feature and configured for some other Ships.
But in this case there is **no combat** at all, the Ship has a small chance to completely evade to a harbour.
(It escapes from the attacker before being caught in combat at all. thus it is not "fleeing from combat".)

**Withdrawal:**
Attacking Unit (usually the stronger force) ends combat because the loses are too big / costly.
--> This should only be used for Units that **can attack**.

**Evasion:**
Defending Unit flees before the combat starts because the attacker is superior. (e.g. Caravel running away from Pirates)
--> This should only be used for Units that are **defensive only**.

------------

**Fleeing:**
Running away as losing force from combat ... This is not what we want, as it would be very annoying for gameplay.
Also considering history, this resulted usually in total defeat without chance to regroup. (90% of the cases)

------------

**Summary:**
Considering DLL everything is working as it should. (Please do not change anything there.)
If there are still some "defensive only" ships that have withdrawal chance it **should be removed** from **XML**

**Comment by victorxup** [comment] 2024-01-10 12:42
> Considering DLL everything is working as it should. (Please do not change anything there.)
> If there are still some "defensive only" ships that have withdrawal chance it **should be removed** from **XML**

Without going much into details, I agree with that

**Comment by victorxup** [comment] 2024-01-11 00:19
The same applies to Great General and Brave Lieutenant. 
They cannot attack, but have extra withdrawal bonus, which is **never** applied.

Another aspect about this issue:
Extra Withdrawal chance can be gained via promotions. But gained this way Extra Withdraw will also never be applied to defensive only units.
Thus I think, it should be explicitly specified in promotion descriptions and unit help, that extra withdraw chance is only applicable for attack, e.g.:
_<English>[ICON_BULLET]Withdrawal chance **on attack**: %d1_Amount%%</English>_ instead of 
_<English>[ICON_BULLET]Withdrawal chance: %d1_Amount%%</English>_
Otherwise the player can be misleaded about what he's gonna get with this promotion.

Also I want to notice that some units currently seem much stronger, than they really are, e.g:
Smuggling Ship with extra withdrawal chance 30%, which is never applied, since the unit is defensive only.

**Comment by Schmiddie1979** [comment] 2024-04-02 22:09
I think we can close this issue because it seems that it has been done - all withdrawal chances for defensive only units already seem to be removed. I could not locate any further of them.

**Closed as completed by Schmiddie1979** 2024-04-02 22:09 UTC
