### ISSUE TITLE
Distribute stone across the map

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#206] opened 2018-11-03 12:25 UTC
[Forum thread](https://forums.civfanatics.com/threads/stone-age.638012/#post-15256797).
Gigantic maps can make huge areas without any stone at all.

**Comment by ShadesOT** [comment] 2018-11-03 18:19
That is a feature, not a bug. Until the player builds a city next to the mountains, there simply is no stone production in the colonies. The player has to buy it. First from the king and later from port royal. It is a challenge. Let's not nerf this challenge.

**Comment by ErikSandbraaten** [comment] 2018-11-05 09:06
I also disagree with redistribution since this is part of the challenge. If we allow this, we wouldn't we also just ensure that there's a peak with gold conveniently placed near each of the players' start positions ?

**Comment by raystuttgart** [comment] 2020-01-08 12:41
Stone does not need the Bonus Ressource.
It can be produced on any mountain. (Unless it was changed in RaR after 2.5)

With an Expert Stone Cutter you can still get enough stone from a normal mountain.
And if you don't have mountains nearby, well yes you need to buy it.

Im my games I never really had an issue with Stone.
(But I usually play quite well balanced maps.)

**Summary:** 
I would leave it as it is as well.
For me there is no need to make the Bonus Ressource more common.

**Comment by raystuttgart** [comment] 2022-11-27 18:14
Let us please close this, nothing is ever going to happen here.
The Maps have been overhauled anyways and Terrains and Features also balanced differently since then.

**Closed by raystuttgart** 2022-11-27 18:14 UTC
