### ISSUE TITLE
Invalid cache assertion failure in CvPlot::hasYield() when conquering a native settlement

### ISSUE THREAD

**Issue by NoFreeUsernameDammit** [We-the-People-civ4col-mod/Mod#178] opened 2018-10-14 15:28 UTC
Taking the native settlement close to Jamestown results in crash everytime I do this. Any way to resolve (short of "leave them alone")? I got pretty close to perfect position, once I get rid of those buggers and Russians.

[QuickSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2476540/QuickSave.zip)

Version is beta 6.

**Comment by Nightinggale** [comment] 2018-10-14 15:41
It's an assertion failure, not a crash. If you click "ignore always", then you can continue to play. It warns that it failed to update a certain cache when you gained a plot within range of your colony. If you save and load, you set the cache correctly.

It's still a bug, but not a crashing bug. It will make citizen placement (particularly automated/AI placement) behave incorrectly.

The issue is in CvPlot::hasYield()

**Comment by Nightinggale** [comment] 2018-10-14 17:02
Fixed. The problem was that the water plot between the two cities transferred ownership to the native settlement, then the settlement was destroyed and the plot moved back. Since the settlement didn't have docks, it viewed the water as a non-productive plot and once given back to Jamestown, the cache informed the AI (auto unit placement) that the plot wouldn't produce any yields, hence avoid. The assert message itself wasn't a bug, only an alert that the game detected a hard to discover bug had occurred. The bug has been in RaR for years, yet it haven't been discovered until today.

Now the cache updates whenever a plot change which city it belongs to, meaning the bug should be gone for good.

**Closed by Nightinggale** 2018-10-14 17:02 UTC
Labels: bug
