### ISSUE TITLE
Development: Scrollable scorelist disables the ability to load units in colony screen

### ISSUE THREAD

**Issue by windock** [We-the-People-civ4col-mod/Mod#553] opened 2022-02-07 17:48 UTC
![2](https://user-images.githubusercontent.com/79237/152842972-bae36238-1d15-4f7f-9af9-22d9df7c2a56.gif)

Can be reproduced in development branch. Cannot in 3.0.1.
City screen does not allow drag-n-drop of goods to transports. Some parts of the UI (Governor button) has click areas not corresponding to graphics.  I use 1920x1080 resolution. However, other resolutions on my monitor have the same issue. Opening app in windowed mode does not help with the issue.
Attaching a save file
[windock AD-1699-January.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8017517/windock.AD-1699-January.zip)
.

**Comment by Nightinggale** [comment] 2022-02-07 19:29
Confirmed though I currently has no idea why. Looks like the DLL code works fine (at least everything I checked) and if you click on the load button on the main map the load menu pops up and that one seems to work. In other words it seems to be an issue with the main interface python file. The only thing which changed in that file is the scrollable score list.... no idea how that one would cause this though. Maybe the drawing engine has it drawn, hidden and still in front of the window. Something to investigate.

There is however another issue with this savegame, though I'm not sure if it's related. The savegame file tells that the player (you) has 722 units. However when doing a head count there are 723 units. Did you add a unit using world builder?

**Comment by MrZorG33** [comment] 2022-02-07 21:47
@Nightinggale  this has already been discussed [here](https://github.com/We-the-People-civ4col-mod/Mod/issues/360).

**Comment by windock** [comment] 2022-02-07 21:48
I have not added any units. Merely added debugging options, logging, etc.
The history of this file is, I have been playing with 3.0.1, and got a crash on the end turn (unknown reason). Compiled dll, loaded into "development" branch, and started to work.

**Comment by MrZorG33** [comment] 2022-02-07 23:41
@windock this is already fixed in Plains

**Comment by raystuttgart** [comment] 2022-02-08 08:56
Yes, I had fixed it in Plains already.

**Closed by raystuttgart** 2022-02-08 08:56 UTC
Labels: bug

**Comment by windock** [comment] 2022-02-08 14:15
It seems to be fixed. I started a new game in Large map, and there are no issues.
