### ISSUE TITLE
Reproducible CTD when working Huckleberries

### ISSUE THREAD

**Issue by MatthewForrester** [We-the-People-civ4col-mod/Mod#894] opened 2023-10-02 16:08 UTC
**Steps to reproduce**
1. Load the following save in WTP 4.02:
[Hernan Cortes AD-1599-January.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/12784232/Hernan.Cortes.AD-1599-January.ColonizationSave.zip)
2. Open the city of La Isabela
3. Move any tile-working unit to the extreme top right-hand tile, which contains Huckleberries.

**Expected result**
The unit works the tile to produce Huckleberries.

**Actual result**
Crash to death.

**Observations**
I don't know whether this bug is specific to Huckleberries, working top-right-hand corner tiles, or something else. I can work the top-left-hand corner tile without problems though. I will update this post if I gather more information.

**Notes**
WTP: 4.0.2 from Github.
Civ4Col: Steam original_release_unsupported beta
OS: Ubuntu 22.04.3

**Comment by raystuttgart** [comment] 2023-10-02 16:16
This sounds like there may be a bug with the KFM that is triggered when the Plot is worked.
But it would be strange if this would not have already been noticed and reported months ago ...

As there is a savegame however it may be analyzed what actually causes the CTD.
Also it will be easy to test if Huckelberries being worked always cause a CTD.

**Comment by Schmiddie1979** [comment] 2023-10-02 19:34
I can't reproduce the crash. Works fine for me. I can unse every unit for work on this plot. Hence, huckleberries work fine so far for me.

**Comment by Schmiddie1979** [comment] 2023-10-02 20:32
Nevertheless we found another bug and fixed it. Hence, thank you for reporting - although we can currently not find out what happens in your current savegame.

**Comment by MatthewForrester** [comment] 2023-10-03 13:21
I can work the top-right-hand corner tiles in another city, so that does not appear to be relevant.

I have also made a gif:

![Huckleberries-CTD](https://github.com/We-the-People-civ4col-mod/Mod/assets/38819845/3f27a575-f0ba-4c28-9b90-8124fb5a79be)

The point that looks noteworthy to me is that the crash occurs as soon as the profession choice pop-up opens.

> I can't reproduce the crash. Works fine for me. I can unse every unit for work on this plot. Hence, huckleberries work fine so far for me.

Thank you for taking the time to test this out. As I mentioned in the other thread, did you try to reproduce the setup (4.02/Steam/Linux) as well, or just test in the `-develop` branch?

Prompted by your recent commit in -`develop`, I looked at `CIV4ArtDefines_Bonus.xml` to see whether if there was anything obviously odd about the capitalization of the Huckleberry paths (since in other software that often causes bugs that occur on Linux but not on Windows), but I could not see anything.

**Comment by MatthewForrester** [comment] 2023-10-07 20:39
@Schmiddie1979 I made the same change as your commit, removing the `<KFM>` entry for Huckleberrles, and this prevents the crash occurring according to the reproduction steps.

**Comment by raystuttgart** [comment] 2023-10-07 21:24
Ok, then I think we can close this issue. :)

**Closed as completed by raystuttgart** 2023-10-07 21:24 UTC

**Comment by Schmiddie1979** [comment] 2023-10-07 23:07
Yes.
