### ISSUE TITLE
Crash buying anything from Europe

### ISSUE THREAD

**Issue by Voker57** [We-the-People-civ4col-mod/Mod#173] opened 2018-10-12 16:04 UTC
Savegame: http://dump.bitcheese.net/files/netimyt/Ermak_AD-1502-January.ColonizationSave

Reproduce: go to europe, by anything (for example, weed)

Results: Crash with assert failed.

Version: v2.7.1-beta6, 2-plot city DLL

**Comment by MichaelQuell** [comment] 2018-10-13 12:11
Releatet to #172

**Comment by windock** [comment] 2018-10-15 14:46
Guys, could you tell how to run a game with assertions disabled? I have multiple assertions popping up regularly, including this one, almost every turn.

**Comment by Nightinggale** [comment] 2018-10-15 15:11
Asserts are enabled/disabled at compile time, meaning once you have a DLL with asserts enabled, you can't disable them without getting a new DLL file. You can however click "Ignore Always".

The main reason why asserts are enabled is that it's a pre-release and every time there is an assert failure, it is a bug. Ideally we need to identify and fix every single assert failure and then the game will be a whole lot more stable. However it has turned out that sometimes the bug is the assert check itself.

**Comment by raystuttgart** [comment] 2020-01-22 19:00
Is this bug still existing?
I can hardly believe it.

**Comment by windock** [comment] 2020-01-23 17:18
@raystuttgart I ended up using one of the develop_* branches the last time I played this mod. I think I have compiled it myself

**Comment by raystuttgart** [comment] 2020-01-23 18:47
Well I was asking because it partially sounded like it was **only an Assert** and **not a real bug** that leads to game crashes?

Also it has the label "Bug to Confirm" which confues me - I joined the team just recently after having been away from modding Civ4Col for more than 2 years so I need to ask.

And also in #172 it says it was already fixed ...

If it was a **real ingame crash bug** and **reproducable** it must have had been **fixed already** because it would be **way too serious** to still go on **doing normal development** without having it fixed.

So what is it now:
(I still don't know.)

- Is it a real ingame bug and still open? --> we need to fix this asap because it sounds serious
- Is it just an Assert but still open? --> we need to fix it but can take some time to do so
- Is it already fixed? --> we can close this issue.

**Comment by Voker57** [comment] 2020-01-24 11:12
It is an assert, you can safely play after pressing ignore or whatever it is. I have no clue why nobody fixed it yet, though, because from what I can see the assert line is there by mistake and can be safely removed (that's what i did to trade normally).

**Comment by raystuttgart** [comment] 2020-01-24 11:48
If I read #172  correctly it was already fixed.
Will thus close this issue as well.

**Closed by raystuttgart** 2020-01-24 11:48 UTC
Labels: BUG TO CONFIRM
