### ISSUE TITLE
fort is not improving

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#886] opened 2023-09-05 12:13 UTC
when there are conquistadors in the fort, the countdown of turns to upgrade does not start.

**Comment by raystuttgart** [comment] 2023-09-12 05:58
Yes, because Conquistadors are Melee Units (that can only fight by attacking directly).
Only Units that have **Guns** or **Cannons** are applicable as Fort Defenders (as they can fight from inside).

The logic explicitly checks for these 2 only:
const UnitCombatTypes eSiegeType = (UnitCombatTypes)GC.getInfoTypeForString("UNITCOMBAT_SIEGE");
const UnitCombatTypes eGunType = (UnitCombatTypes)GC.getInfoTypeForString("UNITCOMBAT_GUN");

The behaviour you noticed is thus intended.
It was designed like that. 

Not all Units should be applicable as Fort Garrison.
(e.g. Also Town Guards and other Melee Units should not.)

But I believe I explained all of that in my original concept many years ago.

**Comment by raystuttgart** [comment] 2023-09-12 05:59
I will thus close it.

**Closed as completed by raystuttgart** 2023-09-12 05:59 UTC

**Comment by MrZorG33** [comment] 2023-09-12 09:29
@raystuttgart I was not aware of this (forts appeared long before I knew about RaR). Thanks for clarifying.
