### ISSUE TITLE
Game freezes at the beginning of the next turn

### ISSUE THREAD

**Issue by digvoo** [We-the-People-civ4col-mod/Mod#267] opened 2019-06-05 07:11 UTC
I have no clue what can be the cause of it. I did a clean install, but that didn't solve it.
Some additional info if it's of any help:
- I'm using Steam and Windows 10 x64
- Device specs: i5-2400 @3.10GHz; 8GB of RAM; SSD;

This might be my case, but can someone confirm, please? https://forums.civfanatics.com/threads/game-freezes-at-end-of-turn.501171/

Savegame from the previous turn is attached.
[Next-Turn-Freeze.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/3255920/Next-Turn-Freeze.zip)

**Comment by Nightinggale** [comment] 2019-06-05 16:08
Often when the game freezes somewhere between the player clicking end turn and the player can play next turn, the cause is something the AI is doing. There is usually no way for the player to figure out the cause. The only real solution is to use the savegame to analyze which code is running while the game is freezing and then work backwards from that to figure out the cause.

**Comment by digvoo** [comment] 2019-06-11 05:04
Update:
First, I removed Navajo from the map in the World Builder and I was able to continue to play.
Then I tried declaring war on them and that also allowed me to continue.
Naturally, they have renounced my missions in their settlements. Just additional info. Might have something to do with that.

And thanks in advance for your help.

**Comment by Nightinggale** [comment] 2019-07-28 15:13
Apparently a human owned whale oil cooker at (46,56) is trying to go to Europe. When setting travel state, it calls CvSelectionGroup::splitGroup. Here it loops through the entire group until no units remain, but it also decides that this unit shouldn't leave the group, meaning it just repeats trying to kick the same unit out of the group and then not do it anyway.

If you think this sounds really weird, then you aren't alone.

**Comment by ErikSandbraaten** [comment] 2019-08-06 16:29
Yeah, the issue is the dodgy logic in CvSelectionGroup::splitGroup which should most likely be replaced with the K-Mod version which according to the commit log contains several bug fixes. However, I am not really sure why splitGroup is used when  it should be enough to unconditionally separate the group with CvSelectionGroupAI::AI_separate(). I am testing now and it seems to have solved the issue.

**Comment by digvoo** [comment] 2019-10-06 16:10
Thank you for the answers.
Is there anything I can do on my end to fix it or just wait for an update?
I assume that editing CvUnit.cpp like ErikSandbraaten did is not enough.

**Comment by ErikSandbraaten** [comment] 2019-10-06 17:40
From my testing it appears to be enough and it arguably is the correct way to split the group.

**Comment by ErikSandbraaten** [comment] 2019-10-06 17:42
Someone needs to merge in the branch that contains the fix and compile a DLL!

**Comment by digvoo** [comment] 2019-10-06 18:18
Ok, thank you. I wasn't sure as I'm new to this. I'll edit the file and load the savegame soon.

**Comment by digvoo** [comment] 2019-10-06 21:20
After the step above I'm still having the same issue. This is the screen it gets stuck on the next turn:

![Screenshot](https://user-images.githubusercontent.com/2730069/66276059-4f4e2700-e88f-11e9-9a8b-75d6b44d4c99.png)

**Comment by digvoo** [comment] 2019-11-25 13:18
Update:
I tried today again this save file to see if I can manually change something from WB.
After removing Train Oil Cooker from Galleon (39, 56), I was able to continue the game with no problems for many turns (edit of CvUnit.cpp like ErikSandbraaten did is of course there).

So, yeah, I didn't remove the initial problem. But all is good now.
Thank you all and sorry for the late update.

**Comment by ErikSandbraaten** [comment] 2020-01-28 07:02
Should be fixed by the commit I referenced earlier

**Closed by ErikSandbraaten** 2020-01-28 07:02 UTC
Labels: bug
