### ISSUE TITLE
Attempt to divide by zero?

### ISSUE THREAD

**Issue by IktaSorlok** [We-the-People-civ4col-mod/Mod#601] opened 2022-06-19 20:07 UTC
so I might've debuged this wrong, but I keep crashing at 1638 (on marathon speed) on every map (originally I thought it was only TAC east coast)
I'll throw the auto save and save game here, as well as the dump file that colonization made, but visual studio claims that it is trying to divide by zero ;
Unhandled exception at 0x07EF2B8F (CvGameCoreDLL.dll) in Colonization.exe.dmp: 0xC0000094: Integer division by zero.

Memory dump will be uploaded to discord as I'm stuck with the 25 MB limit and the small est I can get it in zip is 232 MB
[Save Games.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8936301/Save.Games.zip)

**Comment by IktaSorlok** [comment] 2022-06-19 23:09
ok so I was stupid and forgot google drive was a thing, heres the share link for the memory dump
https://drive.google.com/file/d/1_H4GW5QrkSThOChxnxDH2edQwnL0IppR/view?usp=sharing

**Comment by devolution79** [comment] 2022-06-22 09:29
Try the DLL attached to this post
https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-61#post-16291971

**Comment by devolution79** [comment] 2022-06-22 09:31
This is probably a duplicate of a well-known bug that should have been fixed in 3.0.2

**Comment by devolution79** [comment] 2022-07-13 09:57
It appears that the DLL that I published in my earlier post does contain this fix so this issue is a duplicate.

**Closed by devolution79** 2022-07-13 09:57 UTC
