### ISSUE TITLE
Incorrect tax applied

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#479] opened 2021-06-16 15:31 UTC
Hello guys,

I sold simultaneously gold and silver in Europe and Port Royal (pirate city). The latter reads a 20% tax fee to be deducted, however, it charges the same tax fee I pay in Europe (being 42%).  Is this intentionally or an error...? I couldn't figure it out by reading the colonization colopedia... (yes, some people actually read it... ;-)  )

I have attached the print screen from Port Royal: ![image](https://user-images.githubusercontent.com/61378714/122248081-1c638f80-cec8-11eb-89bf-2abfbc75ff72.png)

Thanks!

Chris
The Netherlands

**Comment by raystuttgart** [comment] 2021-06-16 16:47
Hi vissercp,

that isssue is know.
(It is just a display issue in the sales log - what it displays is wrong)

1. The Tax (actually) bribe actually applied to the gold is correct.
You can test it by doing a sales transaction and calculating the gold you actually get.

2. Just the display in the "Trade Log" is wrong.
It is extremely difficult to change that, because it is so extremely deep in the chain of method calls.

**Comment by vissercsp** [comment] 2021-06-16 17:42
OK - Thanks for explaining, please close this issue. I will ignore the incorrect tax numbers (like I do in real life... ;-o  )

**Comment by raystuttgart** [comment] 2021-06-16 17:43
No, we do not need to close it.
We need to fix it at some point. :)

Just wanted to say that the issue is known and really old.
(It is however also difficult to fix to the way this piece of code was written.)

**Comment by raystuttgart** [comment] 2022-01-16 18:08
Yes, this is fixed now. :)

**Closed by raystuttgart** 2022-01-16 18:08 UTC
