### ISSUE TITLE
Native haggling issue: trade agreement doesn't check if the goods can be fit in the cargo holds available.

### ISSUE THREAD

**Issue by abmpicoli2** [We-the-People-civ4col-mod/Mod#3] opened 2018-09-16 23:23 UTC
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-123#post-15217845

**Comment by abmpicoli** [comment] 2018-09-18 22:46
Just a point: it seems that when the dialog screen is built, there is a validation it the good can fit in the cargo hold: for example, if you only have space for 42 furs in the cargo, even if the native has 240 in stock, it will offer only 42... Maybe this code is the key for the offers...

**Comment by ErikSandbraaten** [comment] 2018-09-20 18:37
Seems solvable, but requires effort. DLL must be modified.

**Comment by ErikSandbraaten** [comment] 2018-09-20 19:12
So I've cleared the most important hurdle by being able to restrict the list of tradeable yields to a given number.

**Comment by ErikSandbraaten** [comment] 2018-09-27 19:50
After I implemented a working fix, I discovered that there are other issues:

- I was able to fit 248 units of food in a single cargo slot! (tested with the save posted on the forum)
- Non-yield units need to be accounted for as well. If there's already a colonist in the cargo, we must deduct this slot.

**Comment by raystuttgart** [comment] 2020-01-28 20:04
This is impossible to fix - the Trade Dialog is in the exe.
Trust me, I had already huge issues hacking into it by my "Bargaining with Natives".

The problem is a bit annoying I agree if you are not careful.
I personally though never had any issue with it - just check your storage.

I will thus close it.

**Comment by ErikSandbraaten** [comment] 2020-01-28 20:12
It's fixable in my opinion by cleverly manipulating the diplo callback functions. I have some code laying around somewhere

**Comment by raystuttgart** [comment] 2020-01-28 20:29
Ok, then if there is a solution for this and somebody wants to spend the effort, I will open it again.
Sorry for closing.

**Comment by raystuttgart** [comment] 2021-11-22 21:18
That issue in the DLL-Diplomacy Dialogues was fixed.

**Closed by raystuttgart** 2021-11-22 21:18 UTC
Labels: bug
