### ISSUE TITLE
[BUG] Civilian unit duplication post attack

### ISSUE THREAD

**Issue by nci-wtp** [We-the-People-civ4col-mod/Mod#532] opened 2022-01-17 16:25 UTC
Sometimes, civilian units get duplicated post attack. Duplicate civilian unit appears out of thin air on successful capture. May be connected to move points not consuming accordingly when attacking multiple civilian units in the same plot.

**Comment by ErikSandbraaten** [comment] 2022-01-25 20:47
We really need a save where this weird event is reproducible!

**Comment by MrZorG33** [comment] 2022-01-25 21:09
I'm monitoring this bug and if it happens again in my test game I'll send a save.

**Comment by nci-wtp** [comment] 2022-01-26 05:05
[bug-unit-duplication-saves.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7939054/bug-unit-duplication-saves.zip)

**Comment by ErikSandbraaten** [comment] 2022-01-26 18:27
Could you also provide some instructions on how to reproduce the issue?

**Comment by MrZorG33** [comment] 2022-01-26 18:57
I tried to reproduce the problem in the Plains version (downloaded 25/01/2022). no problem. when trying to load a save with version 3.0.1, the game crashes.
I can assume that the Steam version is used (not the _original unsupported_) and this bug is precisely because of this.

**Comment by nci-wtp** [comment] 2022-01-27 04:06
@ErikSandbraaten 

1. Load the _post attack_ savefile.
2. The only active unit is Native Mercenary - use it to attack Dutch Missionary. 
3. Behold, the Missionary duplicated. 

For further research, 
1. Load the _previous save_ savefile. 
2. Attack Dutch units in the tile consequently for two turns. 
3. As long as both attacks are successful, you will observe the duplication bug in it's full glory. 

Alternatively, in Worldbuilder place 2x civilian units of AI nation in the same tile, and 2x military units of player nation in a neighbouring tile, then attack. If your attacks are successful, 2x civilian units will become 3x.

@MrZorG33 

1. The bug was originally observed on Plains version from 11 Jan 2021 & DVD version of Colonization. 
2. It is perfectly reproducible on Plains version from 27 Jan 2021 & DVD version of Colonization. 
3. I observe this bug routinely in other games, whenever conditions match. It is absolutely not limited to particular save, you can reproduce it with WorldBuilder.

**Comment by MrZorG33** [comment] 2022-01-27 05:18
hmm.. I'll try to reproduce this problem again tonight.

**Comment by MrZorG33** [comment] 2022-01-27 13:35
I confirm - after attacking a single unit and capturing it, two identical captured units are obtained. out of 5 successful attacks (not all attacks are successful, despite the significant difference in power) 5 led to a duplication of the captured unit.
![image](https://user-images.githubusercontent.com/61798883/151368598-f95e34ad-35b4-4064-9ec7-f79dd696a832.png)

**Comment by ErikSandbraaten** [comment] 2022-01-27 18:27
Confirming, I tested with the bug-unit-duplication-post-attack save and after attacking and winning with the Native Mercenary, the missionary is capture AND duplicated missionary is created!

**Comment by ErikSandbraaten** [comment] 2022-01-27 18:48
Some insight from the debugger:

The first missionary is created here:

			if (!pDefender->getUnitInfo().isNoCapture())
			{
				if ((pDefender->cargoSpace() > 0 && (pDefender->getDomainType() == DOMAIN_LAND || (pDefender->getDomainType() == DOMAIN_SEA && pPlot->getTerrainType() == TERRAIN_LARGE_RIVERS)) || pDefender->getUnitInfo().isTreasure() || (pDefender->isUnarmed() && pDefender->getProfession() != NO_PROFESSION && GC.getProfessionInfo(pDefender->getProfession()).getCombatChange() > 0)) && !GET_PLAYER(getOwnerINLINE()).isNative() && !GC.getGameINLINE().isBarbarianPlayer(getOwnerINLINE())) 
				{
					CvUnit* pkCapturedUnitAfterFight = GET_PLAYER(getOwnerINLINE()).initUnit(pDefender->getUnitType(), pDefender->getProfession(), pPlot->getX_INLINE(), pPlot->getY_INLINE(), NO_UNITAI, NO_DIRECTION, pDefender->getYieldStored());
					pkCapturedUnitAfterFight->setDamage(GC.getMAX_HIT_POINTS() / 2);	
					szBuffer = gDLL->getText("TXT_KEY_UNIT_CAPTURED_AFTER_FIGHT", pDefender->getUnitInfo().getDescription());				
				}
			}

CvGameCoreDLL.dll!CvPlayer::initUnit(UnitTypes eUnit, ProfessionTypes eProfession, int iX, int iY, UnitAITypes eUnitAI, DirectionTypes eFacingDirection, int iYieldStored) Line 1561	C++
 	CvGameCoreDLL.dll!CvUnit::updateCombat(bool bQuick) Line 1484	C++
 	CvGameCoreDLL.dll!CvUnit::attack(CvPlot * pPlot, bool bQuick) Line 3428	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::groupAttack(int iX, int iY, int iFlags, bool & bFailedAlreadyFighting) Line 2670	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::continueMission(int iSteps) Line 991	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::startMission() Line 962	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::activateHeadMission() Line 4179	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::insertAtEndMissionQueue(MissionData mission, bool bStart) Line 4035	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::pushMission(MissionTypes eMission, int iData1, int iData2, int iFlags, bool bAppend, bool bManual, MissionAITypes eMissionAI, CvPlot * pMissionAIPlot, CvUnit * pMissionAIUnit) Line 454	C++
 	Colonization.exe!004f25d0()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for Colonization.exe]	
 	Colonization.exe!00452bc6()	Unknown
 	Colonization.exe!00412a67()	Unknown
 	Colonization.exe!0068ca48()	Unknown
 	Colonization.exe!004cf906()	Unknown
 	Colonization.exe!008fc04f()	Unknown
 	[External Code]	

The second is created here:

CvUnit* pkCapturedUnit = GET_PLAYER(eCapturingPlayer).initUnit(eCaptureUnitType, eCaptureProfession, pPlot->getX_INLINE(), pPlot->getY_INLINE(), NO_UNITAI, NO_DIRECTION, iYieldStored);

>	CvGameCoreDLL.dll!CvPlayer::initUnit(UnitTypes eUnit, ProfessionTypes eProfession, int iX, int iY, UnitAITypes eUnitAI, DirectionTypes eFacingDirection, int iYieldStored) Line 1561	C++
 	CvGameCoreDLL.dll!CvUnit::kill(bool bDelay, CvUnit * pAttacker) Line 577	C++
 	CvGameCoreDLL.dll!CvUnit::updateCombat(bool bQuick) Line 1579	C++
 	CvGameCoreDLL.dll!CvUnit::attack(CvPlot * pPlot, bool bQuick) Line 3428	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::groupAttack(int iX, int iY, int iFlags, bool & bFailedAlreadyFighting) Line 2670	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::continueMission(int iSteps) Line 991	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::startMission() Line 962	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::activateHeadMission() Line 4179	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::insertAtEndMissionQueue(MissionData mission, bool bStart) Line 4035	C++
 	CvGameCoreDLL.dll!CvSelectionGroup::pushMission(MissionTypes eMission, int iData1, int iData2, int iFlags, bool bAppend, bool bManual, MissionAITypes eMissionAI, CvPlot * pMissionAIPlot, CvUnit * pMissionAIUnit) Line 454	C++
 	Colonization.exe!004f25d0()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for Colonization.exe]	
 	Colonization.exe!00452bc6()	Unknown
 	Colonization.exe!00412a67()	Unknown
 	Colonization.exe!0068ca48()	Unknown
 	Colonization.exe!004cf906()	Unknown
 	Colonization.exe!008fc04f()	Unknown
 	[External Code]

**Comment by ErikSandbraaten** [comment] 2022-01-27 18:57
Why is the capture logic scattered around the code like that. There's at least 3 (4 of you count the convert function) places where a unit is created after loosing the fight!

**Comment by raystuttgart** [comment] 2022-01-28 15:41
Ah ok, I think I understood the bug. :)
It is just because the Missionary is considered "Unarmed".

**Comment by raystuttgart** [comment] 2022-01-28 16:12
@ErikSandbraaten 
The code here should **never** trigger for e.g. a Missionary or Failed Missionary:
--------
The second is created here (CvUnit::kill line 577):

`CvUnit* pkCapturedUnit = GET_PLAYER(eCapturingPlayer).initUnit(eCaptureUnitType, eCaptureProfession, pPlot->getX_INLINE(), pPlot->getY_INLINE(), NO_UNITAI, NO_DIRECTION, iYieldStored);`
--------

Because this condition is not true:

`if ((eCapturingPlayer != NO_PLAYER) && (eCaptureUnitType != NO_UNIT))`

If you e.g. look into the XML:
`
<Capture>NONE</Capture>
`

**Comment by raystuttgart** [comment] 2022-01-28 16:40
Hi guys,
I think I already fixed the bug in XML. :)

**Comment by raystuttgart** [comment] 2022-01-28 16:48
By the way:
To test my theory you could try to e.g. place 

"Indentured Servant" --> Unit Duplication might have happened.
"Missionay" --> Unit Duplication might have happened.
"Free Colonist"  --> Unit Duplication should not have happened.

---

Now after my XML change this should not happen anymore.
(Once it is merged to "Plains".)

**Comment by raystuttgart** [comment] 2022-01-28 20:30
It was fixed with my last commits today.
Had forgotten to close it.

**Closed by raystuttgart** 2022-01-28 20:30 UTC
