### ISSUE TITLE
City Name variable value not substituted 

### ISSUE THREAD

**Issue by TBFGMBHmstepan** [We-the-People-civ4col-mod/Mod#578] opened 2022-03-05 04:08 UTC
![image](https://user-images.githubusercontent.com/69200212/156867043-61d00b66-95b9-4003-9451-6bff76f16f9b.png)

**Comment by Nightinggale** [comment] 2022-03-05 15:17
That bug again? The issue is that unlike normal text generation in programming, each argument can only be used once. In this case because Jamestown is mentioned twice it has to be added as argument twice. There have been other events with the same issue.

**Comment by TBFGMBHmstepan** [comment] 2022-03-05 19:58
> That bug again? The issue is that unlike normal text generation in programming, each argument can only be used once. In this case because Jamestown is mentioned twice it has to be added as argument twice. There have been other events with the same issue.

interesting what is the way the text generation works in this ? out of curiosity i have a programming background

**Comment by raystuttgart** [comment] 2022-04-24 17:12
@Nightinggale I think that this bug is already fixed in "Plains".

Edit:
Just checked I am correct, it is already fixed in "Plains".
We have lots and lots of outdated bug reports, simply because we did not publish ...

I will thus close it.
(As I said, fixed internally.)

**Closed by raystuttgart** 2022-04-24 17:12 UTC
Labels: cosmetic
