### ISSUE TITLE
Bug - Prices in the domestic market not realistic

### ISSUE THREAD

**Issue by raubwuerger** [We-the-People-civ4col-mod/Mod#663] opened 2022-12-09 16:21 UTC
Yerba tea is in high demand but more then 2.000.000 gold pieces are too much ... *g*

See picture below ...
![grafik](https://user-images.githubusercontent.com/7585446/206745434-ce48f5d4-274d-483f-b897-75fcf0e7b428.png)

I don't think the save game will help you much. I compiled the dll yesterday (2022-12-08)

**Comment by raystuttgart** [comment] 2022-12-09 16:36
I think @Nightinggale somehow changes something to the logic.
I thought that would have fixed the issue - but obviously it has to be something else.

**Comment by raystuttgart** [comment] 2022-12-09 16:44
I somehow suspect that it is an issue with corrupted savegame data.
(But that is currently actually just guessing.)

**Comment by raystuttgart** [comment] 2022-12-09 16:53
**@raubwuerger** 
Did this just happen for a single good?
Because if yes, then it is most likely not a systematic bug but somehow corrupted data.

@Nightinggale 
If this is all just about corrupted data, maybe we need to add a check for that.
If that corrupted data is then found it could be corrected back to a reasonable value.

**Comment by raystuttgart** [comment] 2022-12-09 17:20
**@raubwuerger** 
Just to be very certain: You started a **new game yesterday** with new DLL, right?
You did **NOT** just compile a new DLL and **load an old savegame**?

**Comment by raubwuerger** [comment] 2022-12-09 17:26
I compiled it yesterday and started a fresh game.

**Comment by Nightinggale** [comment] 2022-12-09 17:36
> I compiled it yesterday 

I fixed the price bug Monday so it should have been fixed yesterday. For the time being, I made a fix as in loading a savegame will make the prices more reasonable. If it happens again, then we will be 100% sure the bug has not been fixed, but if that's the case, then it will be a mystery because it shouldn't be possible to change the price more than 1 each turn with the code I submitted this week.

**Comment by MrZorG33** [comment] 2022-12-09 17:46
I periodically check the cost of goods on the domestic market. So far I haven't noticed this problem...

**Comment by raystuttgart** [comment] 2022-12-09 18:38
As @Nightinggale the logic should not be able to change the price by more than +1 per turn.
Thus to get to 2.000.000 it would need 2 Million turns, which is not possible.

Thus I really believe that the bug was caused by a rare corrupted save game data.
The fix of @Nightinggale should now however correct such corrupted save game data.

Let us still keep watching the issue to see what happens.

**Comment by MrZorG33** [comment] 2022-12-21 21:52
quite a long game. prices for the same goods in the capital (1) and other colonies (2).

coffee
![image](https://user-images.githubusercontent.com/61798883/209008103-ab1b36e8-bd3a-47ef-a493-02078ffd797b.png) 
![image](https://user-images.githubusercontent.com/61798883/209008176-dc3fac4d-a7d7-4527-a01f-c9c965871a1a.png)

everyday clothes
![image](https://user-images.githubusercontent.com/61798883/209008621-bd8a9669-5dca-42dc-8aec-e1c46905995a.png)
![image](https://user-images.githubusercontent.com/61798883/209008551-e33c466e-2244-44a7-ad76-8b4e3c31b89d.png)

cheese
![image](https://user-images.githubusercontent.com/61798883/209008916-45c91549-8a7d-4724-97a8-3cd64a8978d4.png)
![image](https://user-images.githubusercontent.com/61798883/209008864-798231af-8221-489a-ba67-6ee9478459a9.png)

**Comment by raystuttgart** [comment] 2022-12-22 08:14
Now I am totally lost, because the logic @Nightinggale recently implemented should prevent this ...

**Comment by raubwuerger** [comment] 2022-12-22 10:52
I have made the same observation. My dll is from 2022-12-20.
![image](https://user-images.githubusercontent.com/7585446/209118735-fa254a23-b7c6-41fd-a68a-473dec1510d6.png)
![image](https://user-images.githubusercontent.com/7585446/209118883-bb17ae79-4577-4409-a518-801b3197531e.png)

**Comment by raystuttgart** [comment] 2022-12-22 11:07
This is so strange ... because we never had this in 3.0.1 and I cannot remember anything that changed the **Domestic Price** ...
(At least not before @Nightinggale started to code for fixing this issue that now appears in New_Hope.)

**Comment by raystuttgart** [comment] 2022-12-22 11:15
@Nightinggale
Did I mess up in this method here?
Could this cause the problem?

/Androrc Domestic Market
int CvCity::getYieldBuyPrice(YieldTypes eYield) const
{
	FAssert(validEnumRange(eYield));

	// WTP, ray Domestic Market Events - START
	// we modify the price in case there is a Market Event going on
	int iDomesticMarketEventModifier = getDomesticDemandEventPriceModifier();
	int iModifiedPrice = m_em_iYieldBuyPrice.get(eYield) * (100 + iDomesticMarketEventModifier) /  100;
	return iModifiedPrice;

}

**Comment by raystuttgart** [comment] 2022-12-22 11:22
Yes I think that is the problem.
I will fix this. 👍

**Comment by raystuttgart** [comment] 2022-12-22 11:49
Ok, this should be fixed now.
Still I do not want to close the issue before the fix is tested.

@MrZorG33 @raubwuerger 
Please do me a favour and test this in your next games.
Maybe also run an Autoplay of 300 turns and then check the prices in the Cities.

Thanks.

**Comment by raubwuerger** [comment] 2022-12-22 11:53
Ok, maybe I will be able to test it tomorrow ...

**Comment by MrZorG33** [comment] 2022-12-22 12:16
I will not update the current mod, otherwise I will not make a save for the auto-transport issue. tonight I will make another copy of the mod, already updated and start autoplay.

**Comment by raubwuerger** [comment] 2022-12-23 11:47
@MrZorG33:
Now it is clearly better. The highest price is currently just over 50. What would be a maximum price?
![image](https://user-images.githubusercontent.com/7585446/209331088-15743db2-f6f4-4639-b719-75ceee5af5c8.png)

**Comment by raystuttgart** [comment] 2022-12-23 14:50
Prices like that are completely realistic for high value goods like that especially if there is currently a "Domestic Market Event" that increases prices by 50%.
(And looking at the other prices in the citiy that kind of seems to be the case.)

Also I really believe that the fixe I implemented should have solved the issue.
I will then close this issue - it finally seems to finally be fixed.

**Closed by raystuttgart** 2022-12-23 14:50 UTC
