### ISSUE TITLE
the game start event happened much later

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#447] opened 2021-05-01 22:40 UTC
the event happened again in the wrong place and at the wrong time.

![событие происходит не там где надо](https://user-images.githubusercontent.com/61798883/116795636-20d21580-aadf-11eb-9b09-ba16eb7005ec.jpg)

it feels like it happens in about the same place.

![image](https://user-images.githubusercontent.com/61798883/116795668-5bd44900-aadf-11eb-9172-98d7a3b81a67.png)

**Comment by Schmiddie1979** [comment] 2021-05-02 08:54
Have you updated your files including new DLL? When I started a testgame yesterday it worked perfectly.

**Comment by MrZorG33** [comment] 2021-05-02 18:12
@Schmiddie1979 yes, yesterday I updated the files using GitHub for Desktop and created a new DLL.

**Comment by raystuttgart** [comment] 2021-05-09 09:48
Sorry, I can not reproduce this at all either.
It works perfectly fine for me.

**Comment by MrZorG33** [comment] 2021-05-09 09:57
I'll start a new game today - I'll check it out.

**Comment by MrZorG33** [comment] 2021-05-09 10:40
Play now - ok
Play a Scenario - bug (map - the New World)
![событие происходит не там где надо01](https://user-images.githubusercontent.com/61798883/117568408-ba458c80-b0c8-11eb-8620-777f1f551e3c.jpg)
Custome game - ok
Custom scenario - bug (map - the New World)

it seems to me, gentlemen, we have a problem with the New World map.
the problem with the occurrence of the event does not appear every time. try to run this scenario 5 times - 1 out of 5 events will definitely not happen.

**Comment by raystuttgart** [comment] 2021-05-09 10:45
Check the oiginal plot where it did no trigger "game start event" and let me know:

- Terrain Type
- Coordinates (x, y)

**Comment by MrZorG33** [comment] 2021-05-09 11:30
more than 20 launches of the game:

ocean
66,135
70,165
66,147

perhaps there will be the same tiles somewhere else. need to watch the file

**Comment by raystuttgart** [comment] 2021-05-09 11:39
It is not technically possible that 2 Plots are identical (or have same coordinates).
All I was interested was the Terrain. (But **Ocean** is perfectly fine.)

**Summary:**
No explanation yet.

**Comment by MrZorG33** [comment] 2021-05-09 11:52
the event is not triggered on these three tiles.

**Comment by raystuttgart** [comment] 2021-05-09 12:18
Check again please with the Map Update I just commited.
If you find another of these "Starting Events not triggered, let me know".

I learned again something more about Map Making - but it is incredible effort to fix ...
(I will not do this for every Map ...)

**Comment by MrZorG33** [comment] 2021-05-09 13:36
on the tile with coordinates 66,135, the event is not triggered. tiles with coordinates 70.165 and 66.147 did not occur.

**Comment by raystuttgart** [comment] 2021-05-09 13:51
Did you get the **updated new map** from GIT?
(I commited it 2h ago.)

Because you tell me the **same coordinates** as you **already did**?
If my change did not do anything then I can not help anymore ...

 and I had tried to take care of it.

If it still triggered on that plot, I can **not help** anymore. (Because for me it triggered.)

**Comment by raystuttgart** [comment] 2021-05-09 15:26
Well ok, then I have no more idea ...

**Comment by raystuttgart** [comment] 2021-06-05 05:43
That is fixed now.
(Reworked the map yesterday.)

**Comment by MrZorG33** [comment] 2021-06-08 19:07
um .. "Houston, we have a problem" - I just started a new game on the "New World" map and on the tile with coordinates 109,83 the event did not work))) sorry Ray ...
yes, I updated the files using GitHub for Desktop and created a new DLL.
![image](https://user-images.githubusercontent.com/61798883/121242629-769b9980-c8a5-11eb-9373-f8b34bdcbee5.png)

can i help you somehow?

**Comment by MrZorG33** [comment] 2021-06-08 20:50
I specifically wrote in a previous post - "yes, I updated the files using GitHub for desktop and created a new DLL."

**Comment by raystuttgart** [comment] 2021-06-09 15:33
Ok I reopened the ticket.
I can not solve it since I do not know what causes it ...

Sorry.

**Comment by raystuttgart** [comment] 2021-06-09 15:37
@MrZorG33 
The event is simply triggered once you move (or one turn later) ...
Is that really such a big issue?

**Comment by raystuttgart** [comment] 2021-06-09 15:50
**As Explanation:**

It is this Achievement:
ACHIEVE_ATLANTIC

It is simply by this here:
<bDiscoverEast> --> It triggers when a **"Europe East Plot"** is discovered.

So I checked the coordinates you gave me and **they are** in fact **"Europe East Plots".**

**Comment by raystuttgart** [comment] 2021-06-09 16:03
**Edit:**

Ok, I think I know what the issue is.
(I checked the code ...)

Stupid Vanilla Programmers !!!!!
They worked with GridWidths instead of really checking the Type of Europe Plot !!!

`					if (GC.getAchieveInfo((AchieveTypes)iI).isDiscoverEast())
					{
						for (iJ = 0; iJ < GC.getMapINLINE().numPlotsINLINE(); iJ++)
						{
							pPlot = GC.getMapINLINE().plotByIndexINLINE(iJ);
							if (pPlot->isRevealed(getTeam(), false))
							{
								if (pPlot->isEurope() && pPlot->getX_INLINE() > ((GC.getMapINLINE().getGridWidthINLINE() / 3) * 2))
								{
									bGained = true;
									iJ = GC.getMapINLINE().numPlotsINLINE();
								}
							}
						}
					}
					if (GC.getAchieveInfo((AchieveTypes)iI).isDiscoverWest())
					{
						for (iJ = 0; iJ < GC.getMapINLINE().numPlotsINLINE(); iJ++)
						{
							pPlot = GC.getMapINLINE().plotByIndexINLINE(iJ);
							if (pPlot->isRevealed(getTeam(), false))
							{
								if (pPlot->isEurope() && pPlot->getX_INLINE() < (GC.getMapINLINE().getGridWidthINLINE() / 3))
								{
									bGained = true;
									iJ = GC.getMapINLINE().numPlotsINLINE();
								}
							}
						}
					}`

**Comment by raystuttgart** [comment] 2021-06-09 16:07
Will fix it ...

**Comment by raystuttgart** [comment] 2021-06-09 16:27
It is fixed now. :)

**Closed** 2021-06-09 18:11 UTC
