### ISSUE TITLE
Players facing Crash to Desktop issues : divide by 0 in CvPlayerAI::AI_transferYieldValue, line 9553

### ISSUE THREAD

**Issue by abmpicoli2** [We-the-People-civ4col-mod/Mod#1] opened 2018-09-16 23:05 UTC
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-123#post-15192237 divide by 0 in CvPlayerAI::AI_transferYieldValue, line 9553

**Comment by abmpicoli2** [comment] 2018-09-16 23:10
I haven't found any potential for divide by zero at that line. The comment at the forum was made by devolution. We need to check if the issue resolution is already at this repository.

**Comment by ShadesOT** [comment] 2018-09-17 02:27
the commit history says, devolution fixed this

https://github.com/Religion-And-Revolution-Extended/Mod/commit/3150736f78c030007cbb35a573010f9e68666840

but we should test it with the attached savegame from civfanatics first. 
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-122#post-15128023
imo that would be a thorough way.

**Comment by ErikSandbraaten** [comment] 2018-09-18 08:31
At least two players reported this bug and I did provide them with a "rogue" build where I avoided the division by zero and thus they could continue playing from their savegames. However, I now realize that the problem is much deeper.  It turns out that the gamestate is actually corrupted so the division by zero should never have happened to begin with. 
The release build does not contain asserts, so it is possible for the  stored yields to be a negative number without this being detected due to a bug and thus we detect the consequences elsewhere.

The division by zero probably happens much later and we are thus detecting a symptom and not the cause.

This issue would not have been possible if the asserts were enabled to begin with, however they do slow the game down a fair bit. In my autoplay session have not been able to reproduce any asserts related to this. Since the AI does not appear to trigger it, I think it must be related to non-AI yield logic.

**Comment by Nightinggale** [comment] 2018-09-18 16:38
The debug DLL files are really slow and people would prefer not to use them. However I added a 3rd kind of DLL to the project: Assert. It is intended for beta testing as it does all the assert checks, but at the same time it is optimized to make the game playable.

Unrelated to DLL types, we should keep some 2.7 branch for bugfixes while we develop new features in other branches. We can then talk about release candidates with Assert DLLs and all that for making a stable 2.7 branch build.

**Comment by ErikSandbraaten** [comment] 2018-09-19 06:49
We could selectively enable some asserts related to yield storage calculation and have them be active in a release build. This shouldn't slow the game down since we probably only need the ones related to human interaction with yield storage (due to this never happening in autoplay, at least to my knowledge )

**Comment by ErikSandbraaten** [comment] 2019-01-10 11:18
Pretty sure the crash issue has been resolved by my earlier "fix". The discussion has been derailed quite a bit so I'm closing this.

**Closed by ErikSandbraaten** 2019-01-10 11:18 UTC
Labels: EFFORT = SMALL, bug
