### ISSUE TITLE
Relations with king suffer greatly from hire of single soldier

### ISSUE THREAD

**Issue by yanidubin** [We-the-People-civ4col-mod/Mod#277] opened 2019-08-30 12:50 UTC
This is such a departure from my recollection of RaR that I suspect it is a bug not an intentional nerf.

In RaR, when buying troops from your king, as I recall you could buy a full set of the 6 (or is it 7?) troop types, and incur a resultant -1 in relations due to being a drain on his military. Hence if relations were merely average, you could buy many troops (price keeps going up, but moderately), with the hit in relations going up once per **set** of troops purchased.

In my WtP 2.7.1.1 game, I bought exactly 1 troop, many turns ago and over time his dissatisfaction has increased from -1 for just a single unit to -5 without any further hires. This seems totally out of kilter with expectations, and indeed I cannot even get more than a few more before the relationship is so poor he won't sell any more.

I.e. the impact on relations has increased by some 35 times, which is why I believe it is a drastic departure from previous versions and am assuming is bug rather than a redesign as it more or less breaks this whole feature rather than it being quite viable. It also seem broken that impact increases over time - you'd think if anything he'd be annoyed if you purchased too often, and the hit would decay. As things stand, I could have got more troops out of him in a burst (maybe as many as 8) than if spread over time - I hate to think what the fallout would now look like if I had though, and I was now at -40 instead of -5 as a result! If that is the case I would say even if you have intended to nerf it, it'd have been better to disable it rather than leave possiblity of game breaking decay in relations later on.

Is there some deeper mechanism involved here (e.g. some ratio on how much king has earned from taxes vs value of troops purchased)? Or is it straight forward and completely broken (intentionally or otherwise)?

**Comment by Alignn** [comment] 2019-08-30 16:58
Doesn't that stat get used as a sort of general dislike bar that ticks up as your colony develops? I believe I've seen it increase even if you never ask the King for anything. 
Maybe it's for when you increase your military strength, as the King has to spend more on the REF to keep up?

**Comment by MichaelQuell** [comment] 2019-08-30 18:14
> 
> 
> Doesn't that stat get used as a sort of general dislike bar that ticks up as your colony develops? I believe I've seen it increase even if you never ask the King for anything.
> Maybe it's for when you increase your military strength, as the King has to spend more on the REF to keep up?

Thats correct!

**Comment by LibSpit** [comment] 2019-08-31 03:54
I would also say being able to buy a batch of six is excessive. To my understanding of the mechanic buying troops from the king is really to enable security for your early colonies (1, 2, 3, maybe) If you are looking to hire yourself an army, you are supposed to take mercenaries from the docks.

I could see a situation where being at war would change things as then you are asking the king for help to prosecute an action, so then acquiring an army infantry, cavalry, cannons makes more sense as the threat is much greater. (To the crowns sovereignty in the new world)

**Comment by raystuttgart** [comment] 2022-11-27 18:10
There are lots of misunderstandings in that post.
Let us please close this, nothing will ever happen related to this.

Generally in RaR and WTP there is no difference when hiring Troops from King.
The other negative modifiers must have been caused by e.g. Events or other features.

**Closed by raystuttgart** 2022-11-27 18:10 UTC
Labels: BUG TO CONFIRM, BALANCE ISSUE?, AI
