### ISSUE TITLE
No archbishop?

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#359] opened 2020-02-25 07:21 UTC
Hey Guys,

Question: the bishop unit is still available, but the archbishop is not in the diplomacy screen. Does that mean that you cannot receive assignments anymore and eventually receive a bishop? I checked if this is a known issue but couldn't find anything here. Can either one of you explain me if this is a bug or not?

**Comment by raystuttgart** [comment] 2020-02-25 08:50
If the Archbishop is not in the Diplomacy Screen, then that is a **bug**.

But we need to know what you did exactly at game start. 
(There are ways for users to break this feature by increasing the limit of Players over the standard threshold for the Mapsize. Some Scenario Maps might also be broken because not properly maintained.)

Did you start a Custom Game or a Scenario (Map)?

**Comment by vissercsp** [comment] 2020-02-25 14:59
I play a scenario in a self designed map, that I also use(d) when playing RaR. Would you like me to send the savegame to you?

Following up on your explanation, I started a "play now" game, which indeed shows me the archbishop - which solves the problem. Close post?

**Comment by raystuttgart** [comment] 2020-02-25 17:10
@vissercsp 
If you created your scenario before RaR 2.5 the scenario might not be compatible anymore.
(Because in RaR 2.5 one new Native Nation was added.)

And even if you did create the scenario after RaR 2.5 there are still ways to mess up because the game logic will try to add Wild Animals and Archbishop afterwards and can only do so if the number of free players still allows it.

**Also there are some things to know about creating Scenario Maps:**
Most importantly, you need to **always keep 2 empty Player spaces** for Wild Animals and Archbishop and you of course also need to **consider the number of Kings** that will be added for your Colonial Nations for the max number of Colonial Players and Natives **you set manually**.
(This of course is relative to MapSize of your Map.)

**Summary:**
This is most likely not a bug of the mod (WTP).
Game logic and included maps of the mod (WTP) seem to work.
But there is some "hidden knowledge" about creating maps and scnearios that makes it difficult for non-modders to create WTP maps. (e.g. the number of Native Nations we have)
You can figure it out by checking the XML for **CIV4WorldInfo.xml**.

I will thus close this issue.
If you have questions on map / scenario creation you can also contact us the forum.

**Closed by raystuttgart** 2020-02-25 17:10 UTC

**Comment by vissercsp** [comment] 2021-07-23 17:16
Hello @raystuttgart,

I downloaded WTP 3.0.1 yesterday and noticed I still have the missing Archbishop (AB). Today, I checked the above mentioned XML file (and many others) but I cannot seem to influence the presence of the AB....

So I did a little test, see attached file for details. I started a custom game, and checked if the AB was there - which it was. Entering world builder (WB), I saved the file, closed WB and checked if AB is present - which it was. Entered WB again, loaded the saved file and checked if AB was present, which was not the case...!

I attached the saved game and some screenshots. Can you give me any hint(s) on what I should do to get the AB back in the custom build game...? Or what it is I am doing wrong...? 

Many thanks in advance...

Chris
[No archbishop.docx](https://github.com/We-the-People-civ4col-mod/Mod/files/6870245/No.archbishop.docx)

**Comment by raystuttgart** [comment] 2021-07-23 20:10
**@vissercsp** 
You need to know how to **save a WB save** to keep the Archbishop and Wild Animals. 
If you do not do it properly the Archbishop will be gone.

Please read this thread:
https://forums.civfanatics.com/threads/important-thread-map-creation-for-wtp.662649/

**Comment by vissercsp** [comment] 2021-07-24 09:11
@raystuttgart - solved it, vielen dank für deine Hilfe und den Hinweis.
