### ISSUE TITLE
bug? - zooming out = map becomes black , but clouds remain

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#350] opened 2020-01-19 18:35 UTC

**Comment by raystuttgart** [comment] 2020-01-19 20:05
I think that you are talking about a bug already known quite long - since we introduced "Gigantic Maps" in RaR. (It should also only occur for zooming out in Gigantic Maps.)

It seems like the Map-Resolution / graphic engine of Civ4Col simply cannot handle it.
I personally have **no idea** how to fix it or even **if it is fixable at all** with the current graphic engine.

Maybe one of the other team members does have an idea to fix this though.
It would be nice if we could fix it though - if efforts stay reasonable of course.

**Comment by Nightinggale** [comment] 2020-01-19 20:25
It has been a topic once in a while and the most common theory is that the exe is assigning addresses to rows or plots in general and it simply runs out of address space. If this is the case, then there really isn't much we can do about it.

However never say never. There are other exe issues where we can trick the exe around bugs. It just needs the right idea meaning sometimes impossible tasks aren't impossible.

It would be nice if somebody would take the time to investigate various map sizes to figure out precisely where it cuts off.

- How many plots can we have in total?
- What is the max height?
- What is the max width?

If we figure out the answer to each of those 3 question, then at least we will know how to make a map, which is the biggest possible for the engine without this issue.

There is also an xml file we can play around with, like there is a camera threshold between zoomed in and zoomed out and the problem is only present when in zoomed out mode. What happens if we set it to make it stay in zoomed in mode regardless of how far we zoom out? Is that a solution? If it is, then what about the buttons, which only appear when zoomed out?

So many questions and so far no answers...

**Comment by raystuttgart** [comment] 2020-01-20 15:39
Yeah, I also always had the **feeling** that the "Zooming-out-Black-Map" cannot really be solved really.
At least I myself have no idea **where to start** searching.

**Restricting "how far we can zoom out"** does **not** really **make sense**.
All **other maps sizes** except "Gigantic" **do not have an issue** with **zooming out to max**.

Trying to figur out the **exact size and height** for the problem to trigger is a bit tricky.
It is basically **try and error**.

And yes, this is **not** a **Civ4Col issue**.
When we first noticed it, we asked **Civ4 BTS modders** and some had run into the **exact same problem** and could also **never solve it either** to my knowledge.

Even if we figure out what the problem is - without finding a technical workaround / solution:
I does not really break anything. When zooming in a little bit again, the map will get visible again. So is it really worth the effort if it turns out to be more than just a little effort?
It only affects Gigantic Maps - but we cannot really remove them again. Many players, including myself are playing only on Gigantic Maps.

**Summary:**
It is not big enough of an issue for me to spend my time and I could probably also not solve it.
I personally and commnity as well could live with it for years already.

But if somebody else is interested to further invest, I of course do not mind.

**Comment by Nightinggale** [comment] 2020-01-20 16:53
> Restricting "how far we can zoom out" does not really make sense.
All other maps sizes except "Gigantic" do not have an issue with zooming out to max.

It's not about how far you can zoom out, but rather when it switches from normal mode to globe mode. Still you point out what the problem is, which is it only affects gigantic maps. The xml file applies to all games regardless of map size and we can't mod that because it's one of the few xml files read by the exe.

I think the only realistic solution is to figure out precisely when this triggers (which number of plots or height or whatever) and make a map accordingly. At the same time let the engine test for this condition. If the game is affected, we could add some sort of notification that we know it happens and it's unfixable. The question is how to add such a notification in a way where it will be read, but without making it annoying.

**Comment by ErikSandbraaten** [comment] 2020-01-20 17:23
I wonder if C2C did something about this ? I know they have a scheme to unload textures and whatnot to reduce memory consumption so perhaps they have a solution for this issue as well.  AND2 and RI also have this feature which I think they refer to as "graphical paging". Even if it does not turn out to help with this particular issue we may benefit from the memory savings. It should be an easy merge as well if my memory serves me right.

**Comment by Nightinggale** [comment] 2020-01-25 15:07
I studied this issue and it turns out that it depends on the map size. However rather than being linked to the actual size, it is linked to the aspect ratio of the map size.

Apparently we need to take the height of the map, divide it by 1.45 and that is the minimum width a map should be to avoid this issue. 108,215 (standard gigantic map with default distance between land and Europe access plots) doesn't work while 148,215 works.

I'm not sure widening the map is a good solution though. The game use 1 GB of RAM when starting a gigantic map. Going to satellite mode (I think that's the internal name for it) allocates more RAM for graphics. 148,215 will require an additional GB of memory, making the total hit 2 GB. That's just when you start the game before you found colonies and stuff, which requires extra memory.

Being a 32 bit application, by default it will crash if it tries to use more than 2 GB memory. It can be [patched](https://ntcore.com/?page_id=371) to allow 4 GB, but then each player has to patch their own exe. I don't like the concept of including a map size, which will crash the game unless the player manually apply a patch first.

I tried a map of 350,148 and it works. It just use 3 GB of memory, not to mention it's unreasonably slow to create.

**Comment by raystuttgart** [comment] 2020-01-25 15:19
Great that you found out more about the issue.
Thanks for investing the time.

We cannot remove the existing premade maps though.

We could however adjust the XML (and size settings in MapScripts) for future maps to be generated by our MapScripts.

**Comment by raystuttgart** [comment] 2020-01-27 16:37
As I understand Nightinggale this will at least partially be fixed by #353

**Comment by jo-oe** [comment] 2023-03-14 15:32
duplicate of #723

**Closed by jo-oe** 2023-03-14 15:32 UTC
