### ISSUE TITLE
Ships can split selection groups to be on multiple plots (causes freezes)

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#482] opened 2021-06-19 23:10 UTC
Steps to reproduce this issue:

1. place a galleon in a colony
2. fill the galleon with treasures
3. add one more treasure to the colony plot
4. control click on a treasure to make a selection group of all the treasures
5. select the galleon and move
6. The treasures in the ship and the treasures left on the colony plot are still linked in a selection group
7. sailing to Europe cause an infinite loop as some, but not all of the selection group sets travel state

This is a vanilla bug.

**Comment by ErikSandbraaten** [comment] 2021-07-22 13:50
Will look into this...

**Comment by ErikSandbraaten** [comment] 2021-07-23 07:51
Confirming!

The easiest fix for now is to call getGroup()->AI_separate() for both the human and AI case in  CvUnit::setUnitTravelState.
There should be little downside to this IMHO

**Comment by ErikSandbraaten** [comment] 2021-07-30 06:41
We need to track down the actual cause. It is strange that forming a group from units that are both inside and outside the transport is allowed!

**Comment by raystuttgart** [comment] 2021-07-30 08:40
Hi guys,

I am not sure but my gut feeling tells me that this may be caused by "Large Rivers" as well.
I currently can not point the finger to the specific piece of code. 

But **"Boarding Units"** are **"Land Units"**.
And **"Transporting Units"** are **"Ships"**. (at least in the cases where we had this errior.)

So sorry if "Large Rivers" causes so many issues in the afterrun.
But the concept really sounded interesting and it seems that players really like to play with it.

**Comment by ErikSandbraaten** [comment] 2021-08-03 11:28
This problem is definitely unrelated to large rivers so you are in the clear ray :)

**Comment by ErikSandbraaten** [comment] 2021-08-03 11:33
Ok, here are my proposal:

- Implement the simple fix that I mentioned (and tested). There's really no point in preserving groups when traveling to Europe anyhow. Note that units inside a transport is NOT in same group as the transporter. 
- Find a way to prevent the user from forming a mixed groups units in and outside a transport.
- Add additional assertion checks for units in a group being in different plots (which doesn't make sense)

Note that there's been a lot of fixes to group handling in K-Mod so it is likely that this issue (and related ones) will be auto-fixed once we port more of it over to WTP.

**Closed** 2022-04-17 11:35 UTC
Labels: bug
