### ISSUE TITLE
Branch 2.7.2 with lots of "????" placeholders instead of the actual texts...

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#236] opened 2019-01-05 17:49 UTC
Hi, everyone, I'm using branch 2.7.2 , and I'm witnessing this in my game.... 
![image](https://user-images.githubusercontent.com/1733170/50727386-5c23cb80-1101-11e9-9a11-3319713261e0.png)
![image](https://user-images.githubusercontent.com/1733170/50727394-7cec2100-1101-11e9-8fc8-57b9ac08f7e8.png)

**Comment by Nightinggale** [comment] 2019-01-05 18:11
The problem is af7a548171e314db96abd73d9399e79a93119816

The idea is to convert the files to utf8, which would make it a whole lot easier to translate. At the same time the files are now organized into one file for each xml file. The concept is really nice for people who works with the text strings.

The problem is that the scripted conversion worked flawlessly in most files and apparently all the files I checked manually. However a few files failed and placed ???? for all languages in some (all?) strings in those files.

**Comment by Nightinggale** [comment] 2019-01-05 19:17
I'm now fixing this manually by looking up the strings in 2.7.1 and copying those for each file affected. Luckily it only affects buildings and units, but not building/unit classes or any other files.

Locating the building strings reveal that RaR is a mess regarding strings. I'm going through the buildings alphabetically, have reached C and has so far found building strings in 4 different files, none of them named in a way to hint that they contain building strings.

**Comment by Nightinggale** [comment] 2019-01-21 21:03
Fixed in
2ad08b8ebababdee20d1f7e08860b489aa271196
75308373784dd2144fb478bab841b0b0b9d02f21

**Closed by Nightinggale** 2019-01-21 21:03 UTC
