### ISSUE TITLE
Continental Guard too big

### ISSUE THREAD

**Issue by alexandr-** [We-the-People-civ4col-mod/Mod#230] opened 2019-01-02 12:07 UTC
The bounding box of the "Continental Guard" (the unit with the big flag) is too big, in the attached screenshot the position of this unit will prevent selecting the Admiral diagonally and even the city 2 plots above.

![img_5444](https://user-images.githubusercontent.com/6338481/50591307-368f8b80-0e8f-11e9-8a93-97e984f75367.png)
(using 2.7.1.1)

**Comment by MichaelQuell** [comment] 2019-01-02 19:35
I can confirm this!

**Comment by Schmiddie1979** [comment] 2019-01-26 11:36
This is strange. I checked the bounding box in blender and it seems to be fine. However, I will see if I can find out more.

**Comment by Schmiddie1979** [comment] 2019-01-27 20:05
Ok, it seems that it has to do with the matter that the graphic is a mess of different graphics, that has been mixed with nifskope a long time ago. I ever disliked this unit graphic. I assume it would need just as long to repair this files as to create a better and tidy unit. This is a nice little project to revive graphic modding...I will see if I can create a better unit graphic for the Guard

**Comment by alexandr-** [comment] 2019-01-27 20:12
Yes, it is different compared to all other units!

**Comment by Nightinggale** [comment] 2019-01-27 20:18
One thing I would like to point out when messing with this is that since starting WTP, I have learned that the delay at startup comes from some sort of idexing of graphics files like nif, kfm, dds etc. This means the game will start faster if units can share files. For instance if there is just one flagbearer with a reskin for each country rather than a full set of files for each country.

I'm not saying we should drop unit graphic diversity, but it's something to keep in mind in the cases where sharing makes no or close to no difference ingame.

**Comment by Schmiddie1979** [comment] 2019-01-27 23:02
This already the case. All flagbearer share the same files with the exception of the flag.

**Comment by raystuttgart** [comment] 2020-01-28 19:37
@Schmiddie1979 

Does this issue still exist?
If yes, can it be fixed?

If the issue does not exist anymore, simply close it. 👍

**Comment by raystuttgart** [comment] 2021-11-22 21:15
Already fixed now in Plains.

**Closed by raystuttgart** 2021-11-22 21:15 UTC
Labels: bug, 3D model
