### ISSUE TITLE
Border expansion on turn that unrest ends = no border expansion happens

### ISSUE THREAD

**Issue by Alignn** [We-the-People-civ4col-mod/Mod#516] opened 2021-12-17 18:30 UTC
Savefile attached:
[test.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7737068/test.zip)

My colony is in unrest due to an event a couple turns earlier (jungle being burnt down by pranksters). When I end the turn, I get (among other things) a notification that the colony's borders have expanded, however they do not appear to actually do so. Opening the colony view shows that I cannot work the outer tiles, and yet I need 300 culture for the next expansion, as would be expected for border expansion nr 2.

**Comment by raystuttgart** [comment] 2021-12-17 18:39
You may need to **wait** until the **unrest is over**.
(Durin Unrest you can **NOT** assign workers to another plot.)

Unrest --> City is in chaos --> no reassignment of workers

**Comment by Alignn** [comment] 2021-12-17 19:14
Border expansion isn't affected by workers, is it? Culture is generated by buildings, not colonists. 

The issue wouldn't arise if workers generated culture, since workers do not produce anything during unrest - with no culture, the border expansion wouldn't happen, thus avoiding the bug.

**Comment by raystuttgart** [comment] 2021-12-17 19:17
Did the border expand **after the Unrest** or not?
If it did not, then it is a bug.

**Comment by Alignn** [comment] 2021-12-17 20:56
It did not expand, I just got a message saying it did. Here's an image of the turn after:
![culture level 2](https://user-images.githubusercontent.com/18351802/146606800-1788a9e5-d711-4a9c-8715-40dbc378a7f0.png)

**Comment by raystuttgart** [comment] 2021-12-18 11:13
Hm, it seems to be related to this peace of code.
(Currently can not test properly with old saves, since the branch I am working on is months more advanced.)

`void CvCity::setOccupationTimer(int iNewValue)
{
	bool bOldOccupation;

	if (getOccupationTimer() != iNewValue)
	{
		bOldOccupation = isOccupation();

		m_iOccupationTimer = iNewValue;
		FAssert(getOccupationTimer() >= 0);

		if (bOldOccupation != isOccupation())
		{
			updateCultureLevel();

			AI_setAssignWorkDirty(true);
		}

		setBillboardDirty(true);
	}
}`

**@Nightinggale** 
Do you have a bit of time to check the savegame above?
(I am currently not able to simply stop what I am working on.)

Does occupation really cause a bug in "City Radius expansion" **after it is over**?
(Potentially it already increase the "CultureThreshold" to the next level" (but not the Culture Radius).

**Comment by raystuttgart** [comment] 2021-12-18 11:18
Ah !!!!
I found something.

This bug seems to have been caused by @vetiarvind years ago- and I have no idea why he coded this.
He removed the "is Occupation()" check from the actualy "updatedCultureLevel()" which may be called by other methds !!!

`

void CvCity::updateCultureLevel()
{
	if (getCultureUpdateTimer() > 0)
	{
		return;
	}

	CultureLevelTypes eCultureLevel = ((CultureLevelTypes)0);

	//if (!isOccupation()) // R&R mod, vetiarvind, bug fix for units "disappearing" during disorder
	{
		for (int iI = (GC.getNumCultureLevelInfos() - 1); iI > 0; iI--)
		{
			if (getCulture(getOwnerINLINE()) >= GC.getGameINLINE().getCultureLevelThreshold((CultureLevelTypes) iI, getOwnerINLINE()))
			{
				eCultureLevel = ((CultureLevelTypes)iI);
				break;
			}
		}
	}

	setCultureLevel(eCultureLevel);
}

`

@Nightinggale 

I have no idea why he removed that check.
It was during my 2 year absence from the modding scene.

He writes that he wanted to fix a bug, but I do not understand which bug that might have been ...

**Comment by raystuttgart** [comment] 2021-12-18 11:46
I was right, tested and confirmed my bugfix.
The next commit will have this solved.

@Alignn
Thanks for reporting.
Sorry, for doubting your bug report. I should have checked first, but I thought I knew the code.
I had not known that one of the less experienced modders had messed with that code (years ago after I had left RaR).

**Closed by raystuttgart** 2021-12-18 11:46 UTC

**Comment by Alignn** [comment] 2021-12-18 19:42
No problem, I'm just happy to contribute!
