### ISSUE TITLE
Salt Production 1/10

### ISSUE THREAD

**Issue by stepik-tug** [We-the-People-civ4col-mod/Mod#382] opened 2020-09-27 20:31 UTC
I have a Game where i should be producing 3 Salts i dont get any each turn , i have overproduction of rock salt so that is not the problem .  When i use my space trader and a colonist for producing salt i get +10 Salt production but at the end of the turn i get 1 Salt .

**Comment by Nightinggale** [comment] 2020-09-27 20:34
A savegame would be nice. Not only will it make it easier to find the problem, it will also allow testing if the problem is fixed.

**Comment by stepik-tug** [comment] 2020-09-27 21:17
Im sorry didint think of that , here you are , look in new amsterdam city middle of the map , salt production is +2 ,with enought rock salt but no salt is produced . 

[buggy salt in amsterdam save game_.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/5289091/buggy.salt.in.amsterdam.save.game_.zip)

**Comment by stepik-tug** [comment] 2020-09-27 21:18
I also experienced that the one 1 Salt i Produce when i produce +10 salt , disapears at next turn or some turn after that .

**Comment by raystuttgart** [comment] 2020-09-28 17:14
@stepik-tug 
You know that there are e.g. mechanics in the game like e.g. **"Domestic Market"** or **"Warehouse Overflow"** ?
Are you sure it is not related to those? (Please check the "Domestic Market Demand")

**Comment by stepik-tug** [comment] 2020-09-28 18:14
> @stepik-tug
> You know that there are e.g. mechanics in the game like e.g. **"Domestic Market"** or **"Warehouse Overflow"** ?
> Are you sure it is not related to those? (Please check the "Domestic Market Demand")
> 
> **Especially Salt** is a good that is highly demanded on Domestic Market and thus **consumed a lot by your Citizens**.
> (Of course they pay you for that - you should get messages for Domestic Market on the Screen.)

So it is consumed by domestic market in the same turn that it is produced ? then i guess this is more Issue with the Displaying of the +Number Production view at the resource if everything is consumed before in storage then domestic market substraction would be very sensible to be displayed alongside the tooltip which reports how much is produced and substracted because of hapiness and so on , as this number in my view should reflect the total production , and while looking at it i cannot tell why my goods went away or never appeared but it still says i have neto positive production which is confusing.

**Comment by raystuttgart** [comment] 2020-09-28 19:40
Both "Production" and "Domestic Market" happens after you press "End Turn" button.
So sure, every turn you produce something and every turn your Citizens consume something - how else should it happen?

Speaking about "same turn" does not really help a lot - it simply both happens "during end turn logic".
Lots of things happen during "end turn logic". (It is at least 10 different logics the city runs in "end turn logic".)

And yes, it is **not considered** in "Net Production" Number.
But **Mouse Over the Yield** will tell you how much the Domestic Demand is.

-------

But the "Total Production" is reflected correctly. 
"Domestic Demand" is sold from **Storage**.

The chain simply looks like this:
Production -> Storage -> Potentially Wharehouse Overflow -> ... -> Sales from Domestic Market (if available in Storage)
(It is one of the last calculations in "City end turn logics" - only few things like e.g. Health / Happiness happen later.)

Domestic Market is thus **not** "consumed from Production".
It really is "consumed from Storage".
All of that stuff simply happens during "end turn calculation".


"Domestic Market" is not production - it is a "Market / Sales" feature - that depends on demand (citizens) and supply (storage).
"Overvlow of Storage" is also not production. The Yields will be lost from Storage as well, not from Production.

-------

WTP (as was RaR) is a lot about "understanding what happens".
There are a lot of new logics you might need to get used to.

-------

Again, check the **"Mouse Over"** that is displayed at the Yield.
(It will show you the Domestic Demand for that Yield and the Domestic Price. Domestic Demand of course can only be fulfilled if enough is stored - which also includes the amount produced that turn.)

Generally however - if somebody has really good ideas to improve UI - nothing speaks against it. 👍 
(Of course it needs a modder willing to implement it.)

**Comment by stepik-tug** [comment] 2020-10-01 23:50
> That is ok - but is simply not bugs. - It might of course be a potential to improve User Interface. (Those features are complex though.)

Ok then it is an Issue . 

> At least 50% of bug reports we get are from new players because they do not understand a feature - not because there is a bug.

So it is a relatively speaking big  Issue i guess. 

> Generally however - if somebody has really good ideas to improve UI - nothing speaks against it. 👍

I guess improving the ui so 50% of people dont regard "features" which are not easily understandable from the UI is probably a good idea.

**Comment by raystuttgart** [comment] 2021-04-24 10:25
So ok, the features (Domestic Market and Warehouse Overflow) **work as designed**.
Thus this is **no bug**.

However, it has been reported several times because **new players simply do not know** these new (Domestic Market) or heavily changed (Warehous Overflow) **complex game mechanics**.

Actually it is **100% obvious for any experienced player** that there will be "Warehous Overflow" once you take a look at the "Total Storage Amount" and the **Total Production Amount** on the top left of the screen (simply check the Colour).

Every time something like this was reported I could simply check these numbers and explain it to the players.
Never had an experienced player reall ask about that anymore ...

------

**Problem:**
Both are calculate "end turn" - when the player can not move goods or change colonists / professions" anymore thus there is no reasonable way to visualize e.g. "Ware House Overflow", since the data is not available in the middle of the turn while the player still actively makes decisions and changes.

**Comment:**
In the past, the Warehouse Overflow was reported very detailed for every City and every Good.
Player complained and did not want that information anymore because it was "information overflow".
Thus this is also not the solution.

------

**Effort:**
I have no **proper solution** for this other than telling the players "learn the new rules" of the mod and you will understand what goes on.
Once they learned the new game mechanics this is really nothing confusing anymore.

Thus the different times of computation of "City Display during turn" and "actual Production end turn" (of a single Yield) + "Warehouse Overflow end turn" (**total overflow distributed to single Yields by percentages **) make it **too much effort** to change.

This mod is simply not Vanilla.
Game mechanics and algorithms are way more complex and not always easly linear.

**Summary:**
**I will close this issue**, because it is mostly **just a question** about **complex WTP game mechanics**.
Of course it would be a **good suggestion for an improvement** if it was **reasonable effor**t to solve.
(But trust me, the Overflow Mechanic is **not** as **simple to determine before end turn**. Too many variables can change before that.)

**Closed by raystuttgart** 2021-04-24 10:25 UTC
