### ISSUE TITLE
Hurry production fails if there isn't warehouse space.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#87] opened 2018-09-19 04:56 UTC
While I was testing for bug #36, I tried to buy a Governor Palace... And every turn they mentioned that the Governor palace couldn't be completed because we lack some resource...
After some turns I've realized why: when I hurried the palace, warehouse space overflowed. The warehouse adjustment routine seems to happen before building production, and the goods are lost.

**Comment by abmpicoli** [comment] 2018-09-19 05:00
I think we can use one of two solutions here: 
option 1) block hurrying a building if there isn't warehouse space for the goods needed, and show in the hint for the button that this is what is forbidding the hurry. This is interesting , gamewise: it would really make impossible to build advanced buildings if there isn't enough warehouse space for that.

option 2) really make consumption of goods for the production happen before warehouse space overflow is calculated.

option 3) we could make an hybrid of these two: make impossible to hurry a production if there isn't warehouse space, *and* make consumption happen before overflow losses are calculated.

**Comment by ErikSandbraaten** [comment] 2018-09-19 06:39
I proposed changing this mechanic in this post : https://forums.civfanatics.com/threads/proposal-rework-decay-spoiling-logic.620409/

Note that this issue is closely related to #75 so I think we could discuss them in the same context.

**Comment by ShadesOT** [comment] 2018-09-20 20:58
@abmpicoli 
There might be another reason for not being able to hurry the production. The resources in question, need to be tradable in europe. Because they are simply bought from europe (at an insane price I assume) and beamed instantly to the city.

**Comment by ShadesOT** [comment] 2018-09-20 21:05
@ErikSandbraaten 
Your crossreference is correct. And I am currently working to untangle the whole cascade of code in doYields. Currently I am just untangling.

**Comment by ShadesOT** [comment] 2018-10-15 18:44
I had a look at the code regarding this issue. The problem is that the code is sequenced in the following way ...
```cpp
void CvCity::doYields()
{
        doYieldsNeededForRushing();
        doYieldProduction();
        //...
        handleStorageLoss();
}


void CvCity::doTurn()
{
        //...
	doYields();
        //...
	doProduction();
        //...
}
```
... where it would need to be in this sequence ...
```cpp
void CvCity::doYields()
{
        doYieldProduction();
        doYieldsNeededForRushing();
        //...
}

void CvCity::doTurn()
{
        //...
	doYields();
        //...
	doProduction();
        handleStorageLoss();
        //...
}
```
... so the resources, bought to rush the production, are not lost, before the production happened.

**Comment by Nightinggale** [comment] 2018-10-15 20:12
When I looked at the code earlier today, I realized that the overflow handling should be moved to a place where nothing else happens, but for a different reason. Right now it loops yields, each iteration looks up the total storage to calculate the loss. This means the amount you lose of each yield can actually depend on the yield ID, as in is it first or last loop iteration.

We should instead make a function, which calculates how much the warehouse overflows and then have a fixed number through the loop. Also having the overflow before the loop means the function can just return if the overflow is <= 0.

The loop should be from FIRST_OVERFLOW_YIELD to <= NUM_CARGO_YIELD_TYPES.

Expand YieldTypes enums with this: (below NUM_YIELD_TYPES)
```cpp
	NUM_CARGO_YIELD_TYPES = YIELD_HAMMERS,
	FIRST_OVERFLOW_YIELD = YIELD_HEMP,
```
This will reduce the number of iterations by skipping all those yields, which can't overflow. Also it moves the setup of yields from the function to the enum, which makes it more obvious and easier to change later.

NUM_CARGO_YIELD_TYPES is copy pasted from the CivEffect branch.

With a dedicated function it will also be easier to take #181 into account.

**Comment by ShadesOT** [comment] 2018-10-15 20:56
> The loop should be from FIRST_OVERFLOW_YIELD to <= NUM_CARGO_YIELD_TYPES.

Yeah, this is the same topic as in #57 and related issues.

**Comment by ShadesOT** [comment] 2018-10-16 06:35
Should be fixed now. Playtested. @abmpicoli, maybe you can test it too with your savegame?

**Closed by ShadesOT** 2018-10-16 06:35 UTC
Labels: bug

**Comment by abmpicoli** [comment] 2018-10-16 21:13
I don't have it anymore, sorry...

**Comment by ShadesOT** [comment] 2018-10-16 21:15
Keep savegames. Upload them. A savegame that shows a bug, is like catching a thief with his hands in our pockets.

**Comment by abmpicoli** [comment] 2018-10-16 23:28
Just tested by entering debug mode, Player.setGold 0 1000000 and building the colonial congress at a city with no storage. So, I think it is fixed.
