### ISSUE TITLE
Manowar bugs

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#463] opened 2021-05-19 21:16 UTC
release 2.9

having received Manowar from the king, I began military operations against the French and found:
- Manowar can enter natives villages (other warships cannot do this)
![image](https://user-images.githubusercontent.com/61798883/118884707-80158f80-b8ff-11eb-8e4d-b6fcbb7bf98f.png)

- when trying to move Manowar to the tile with the British ship, I was not asked if I wanted to declare war on them. only when moving the Corvette, Frigate and Ship of the Line I was asked about this
![image](https://user-images.githubusercontent.com/61798883/118885012-e0a4cc80-b8ff-11eb-85b4-0b95cdc240e0.png)

differences between Manowar and the Ship of the Line (CIV4UnitInfos.xml)

The Ship of the Line in the description
< UnitAI >
   < UnitAIType >UNITAI_ESCORT_SEA< /UnitAIType >
   < bUnitAI >1< /bUnitAI >
  < /UnitAI >
Manowar doesn't have that.

this is the only difference (if you do not take into account the combat characteristics and the cost of construction).

Does anyone have any suggestions where it might be broken?

**Comment by dcrookston** [comment] 2021-05-20 08:21
I assume it can enter native villages because it is a transport unit, which means it could potentially buy or sell goods. Not sure about the attack dialog box.

**Comment by MrZorG33** [comment] 2021-05-20 09:06
why then can't the Frigate or the Ship of the Line do this?
Manowar has involvement with naval ships, like everyone else.

By the way, the Sloop also belongs to the naval ships, but can enter the villages of the natives and can trade.

**Comment by raystuttgart** [comment] 2021-05-20 16:03
Guys, do not always call everything that is currently not uderstood a "bug". :)

It is basically that the KING has **no** other Ships !
And during the DLL-Diplo-Event you **simply get the same** Ship.

The "ManoWar" is thus designed in a way that the King can enter e.g. Ships.
This is all just balancing of XML and according Rules for e.g. UnitAIs.

There is **no "bug"** in there.
It is working as it was implemented and balanced in XML.

----

Messing with the Ship of the King is a really bad idea.
There are simply reasons that it works like it does.

**If you really insist:**
We can remove "Man-O-War" from the DLL-Diplo-Event "European Wars".
Thus player will not have it anymore.

**Comment by Nightinggale** [comment] 2021-05-20 16:10
I would call it a bug that how it behaves like that is linked to UnitAI. UnitAI tells the AI how to use the unit and it should never influence how it behaves for a human player (unless automated). It also brings up the question if a player should be able to set UnitAI for a unit to something other than the default value. That way the king can do one thing while the new world players can do something else with the very same unit.

This is however not something I really want to dive into at the time being. It's not like there is a shortage of tasks and this doesn't seem urgent.

**Comment by raystuttgart** [comment] 2021-05-20 16:14
It is not a bug guys.
Why does everybody always scream bugs, where there are none ... :(

It is allowed to enter Native Villages because it has cargo space.
That is intended. (Because it could transport goods.)

**Comment by MrZorG33** [comment] 2021-05-20 16:38
1. I didn't scream. a cry in my performance would be like this - EBAAAAAAT!!!)))
2. I am testing the game. and if I find something that is at odds with my idea of normality, I write about it. which I did)
3. I cannot know all the concepts of Colonization. I have only recently begun to understand a little something. however, I am very far from your level. be condescending)
4. _Otherwise we will have players that will try to use it as "Trade Ship" and then scream "I have loaded cargo and now can not enter a village"_. that's why I opened Issue #462

**Comment by MrZorG33** [comment] 2021-05-20 17:16
however, the fact that Manovar cannot start a war, I believe, should not be so.

**Comment by raystuttgart** [comment] 2021-05-20 17:24
@MrZorG33 
Again, the Manowar was not designed for Human Player.
It was designed for King Player.

The fact that I gave it to Human Player does not change that.
It is still technically the same Unit.

King Player does not want to start a War.
And Ships that have cargo slots usually do not do that either.

Please give me some time to maybe code "Rebuild of War of Independence".
All we would change now considering this is basically wasted effort then ...

**If this is really disturbing you:**
The easiest way to solve it is to not give the Unit anymore to Human Player.
The DLL Diplo Event "European Wars" could instead simply e.g. give a "Brigantine".

Then we solved all problems, because Human does not have it anymore.
If you want to do it like that, I am absolutely fine with it.

Actually I later always felt that "Man-O-War" was a bit much ...
(I simply overexagerated the reward a bit in my original design.)
But some players love the "European Wars" because of that ...

**Comment by MrZorG33** [comment] 2021-05-20 17:35
_Please give me some time to maybe code "Rebuild of War of Independence"_.
no problem, Ray)

**Comment by raystuttgart** [comment] 2021-11-27 11:10
Ok this is fixed now.
All War Ships (incl. Man-O-War) trigger "Declare War Message".
The logic now does not just consider "Cargo Space" anymore.

**Closed by raystuttgart** 2021-11-27 11:10 UTC
