### ISSUE TITLE
auto transport does not automatically deliver goods to colonies

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#456] opened 2021-05-09 00:13 UTC
automated transport does not deliver goods for the domestic market from the capital to other colonies.
![не развозятся товары01](https://user-images.githubusercontent.com/61798883/117556549-d0c0f900-b072-11eb-9ea1-237a6b86f191.jpg)

although there are applications for the import of goods in the colonies.
![не развозятся товары02](https://user-images.githubusercontent.com/61798883/117556556-d9b1ca80-b072-11eb-9708-6f9a5de98394.jpg)

however, if all trade routes are selected in the menu of each automated transport, goods begin to be delivered to the colonies.
![не развозятся товары03](https://user-images.githubusercontent.com/61798883/117556558-de767e80-b072-11eb-91ba-706e0b02e01b.jpg)

before, it was enough to automate transport and he began to deal with the delivery of goods for the domestic market. 
this bug needs to be fixed, because with an increase in the number of colonies and automated transports, it is impossible to "catch" every such unit.

**Comment by Nightinggale** [comment] 2021-05-09 11:07
Not a bug. It does as you ordered it to do. You have two numbers:

- import limit
- maintain level

You import when you have less than the maintain level and while importing, you will never get more than the import limit.
You set the maintain level to 0 meaning you told the transports to start importing when you have less than 0 stored. Since you have 0, nothing happens.

You should be aware that the right number is used to trigger both imports and exports. The left number is only used while the right number has activated import.

This is explained in greater detail in my yet to be committed concept pedia text for automated transports.

**Closed by Nightinggale** 2021-05-09 11:07 UTC

**Comment by MrZorG33** [comment] 2021-05-09 13:45
if I understood [this topic](https://forums.civfanatics.com/threads/trade-routes.631219/) correctly, then in the left field I set the import limit. and when the quantity of goods falls to 75%, imports will resume.
in the right field, we indicate the export limit - the minimum quantity of goods that must remain in the warehouse. all surplus will be exported.

however, if this concept has changed, then I would like to see the text of the new concept. even if he is not completely ready. just to understand.
