### ISSUE TITLE
Early game crash at end of turn after choosing church/tavern event

### ISSUE THREAD

**Issue by IFoundabugg** [We-the-People-civ4col-mod/Mod#817] opened 2023-04-13 04:14 UTC
4.0.2

I chose tavern and then the game froze at end of turn - just as the icon was midway changing color followed by ctd. 

Unable to reproduce but I am documenting in case this event produces problems by others.

Also, I was clicking through early game extremely fast - which of course should not be a problem.

**Comment by MrZorG33** [comment] 2023-04-13 06:36
What does "chose" mean? chose to build or clicked on an already built building?

**Comment by IFoundabugg** [comment] 2023-04-13 06:56
I was presented with the  event where you can choose a church, tavern or another option (neither? I forget the other option)
I chose the tavern option. It was the only choice I made that turn and the crash followed after I clicked end turn. It may be unrelated. As I said I couldn't reproduce it. The event didn't come up again. 

Every reload was without the event and without problem.

**Comment by MrZorG33** [comment] 2023-04-13 07:14
Do you have auto-save of the beginning of this turn left? the event must occur.

**Comment by IFoundabugg** [comment] 2023-04-13 07:28
It won't help. It was two turns before and I reloaded it enough and could carry on for ages after.

I think I just broke the game by clicking through things too fast.

**Comment by MrZorG33** [comment] 2023-04-13 07:43
The third option, by the way, is to get gold.
I have never encountered this during test games. therefore, without saving, we will consider this an accidental failure. if it happens again and you can provide a save - reopen this thread. Until then, I'll close it.

**Closed as completed by MrZorG33** 2023-04-13 07:43 UTC

**Comment by Nightinggale** [comment] 2023-04-13 08:40
> I think I just broke the game by clicking through things too fast.

That should not be an issue. If the game crashes, then it sounds like a bug, which needs fixing. However I can't really do anything about a CTD I can't reproduce. I have nothing to test on to pinpoint where and why the crash occurs in the source code.
