### ISSUE TITLE
AI swaps colonists ignores canHaveProfession

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#262] opened 2019-03-11 13:56 UTC
CvCityAI::juggleColonist calls CvCityAI::AI_swapUnits even if the two units can't use each other's professions.

[Forum report](https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-7#post-15400399)

[Dominic AD-1614-July.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2952475/Dominic.AD-1614-July.zip)

**Comment by ErikSandbraaten** [comment] 2019-03-11 16:53
It's in the list of known asserts. I've seen it trigger several times when a slave is attempted to be put in a restricted profession, If I remember correctly

**Comment by Nightinggale** [comment] 2019-03-11 17:26
Even if it is in the list, it's still not a bad idea to have a dedicated bugreport with a savegame where it happens consistently.

**Comment by ErikSandbraaten** [comment] 2020-01-28 06:59
I think is caused by the (mis) feature : 
`
//This suppresses certain checks to all the workforce allocation algorithm to run
//more smoothly (ignore time-consuming checks and swaps)
void CvCityAI::AI_setWorkforceHack(bool bNewValue)
`
I guess we should determine what it would cost in terms of performance to never enable this at all. Hopefully it won't be that bad and the asserts will go away. When the multi threaded job assigner finally gets merged, the extra CPU cycles should not matter much and we should be able to easily pay the cost for more elaborate (and correct) checks

**Comment by Nightinggale** [comment] 2020-01-31 19:17
Maybe we should try to optimize CvUnit::canHaveProfession. If it is as time consuming as we would expect, maybe look into caching. Certain checks are fairly static as in tied to CvUnitInfo and as such could be cached for each unit (or unit info or each unitID in CvPlayer or whatever is the most suitable).

While there is a potential gain, which isn't worthless, I don't think it can be good enough to not justify multi threading. Ideally we can have both.

**Comment by ErikSandbraaten** [comment] 2021-04-09 16:20
Fixed in 2.8.2

**Closed by ErikSandbraaten** 2021-04-09 16:20 UTC
Labels: AI, bug
