### ISSUE TITLE
Missing text key

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#955] opened 2023-11-21 09:34 UTC
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/23401480/d1f8808c-1046-4b4c-937c-d60d90b85455)

**Comment by MrZorG33** [comment] 2023-11-21 09:41
There are two similar tags in the mod: TXT_KEY_GLOBELAYER_RESOURCES_NATIVE_TRADE and TXT_KEY_GLOBELAYER_RESOURCES_NATIVE_TRAIN. what did you hover your cursor over?

**Comment by victorxup** [comment] 2023-11-21 10:23
> There are two similar tags in the mod: TXT_KEY_GLOBELAYER_RESOURCES_NATIVE_TRADE and TXT_KEY_GLOBELAYER_RESOURCES_NATIVE_TRAIN. what did you hover your cursor over?

That's just map zoom out

**Comment by MrZorG33** [comment] 2023-11-21 10:23
ok, I found this tag in the Vanilla file. for some reason it was not transferred to the Vanilla_TEXT_XML_key_utf8.xml file in the mod. I'll add this tag to the mod.

**Comment by MrZorG33** [comment] 2023-11-21 10:26
Also, I just checked it myself and saw another missing text, although I clearly remember that I translated the names of these buttons. I'll try to solve this problem.

**Comment by MrZorG33** [comment] 2023-11-21 10:40
@Nightinggale I need help. The thing is that now instead of the vanilla TXT_KEY_GLOBELAYER_RESOURCES tag the TXT_KEY_CONTROL_RESOURCE_ALL tag should be used. but the mod continues to read tags from Vanilla first.
the same with the Vanilla tag TXT_KEY_ACTION_UNIT_ICONS - the tag from the TXT_KEY_CONTROL_UNIT_ICONS mod should be read.

**upd.** The problem is that tags from Vanilla start to appear only in the global view of the map. In normal mode, the buttons display tags from the mod.

**Comment by Nightinggale** [comment] 2023-11-21 11:13
The xml reader is doing stuff it shouldn't do. Rather than trying to figure out what it does, I want to write a new one where I cut out the exe entirely. I highly suspect I can cut out more than 50% of the code anyway because it's bloated and not clean.

**Comment by MrZorG33** [comment] 2023-11-21 11:16
this is great, but why when I did the translation did the tags work correctly?

**Comment by johan-buret** [comment] 2023-11-21 12:20
@MrZorG33 During the cleanup you did on this commit : 
https://github.com/We-the-People-civ4col-mod/Mod/commit/5b635410d87f2f0cdd2dafe45cbaeb1dbde2a835

The missing `TXT_KEY_GLOBELAYER_RESOURCES` Tag was deleted here.

Please restore the file, and make sure the tags you removed are indeed not used anywhere.

**Comment by MrZorG33** [comment] 2023-11-21 12:36
@johan-buret missing tags should not be used because others have been made for them (I have listed them above). Why do you need two tags for one button?

**Comment by Nightinggale** [comment] 2023-11-21 13:03
```cpp
void CvGameTextMgr::setResourceLayerInfo(ResourceLayerOptions eOption, CvWString& szName, CvString& szButton)
{
	switch (eOption)
	{
	case RESOURCE_LAYER_NATIVE_TRADE:
		szName = gDLL->getText("TXT_KEY_GLOBELAYER_RESOURCES_NATIVE_TRADE");
		szButton = "XXX";
		break;
	case RESOURCE_LAYER_NATIVE_TRAIN:
		szName = gDLL->getText("TXT_KEY_GLOBELAYER_RESOURCES_NATIVE_TRAIN");
		szButton = "XXX";
		break;
	case RESOURCE_LAYER_RESOURCES:
		szName = gDLL->getText("TXT_KEY_GLOBELAYER_RESOURCES");
		szButton = "XXX";
		break;
	default:
		FAssertMsg(false, "Invalid option");
		break;
	}
}
```
This is the code inside the dll. It specifies which txt keys it will use and then we will have to use those. If we want to use some other key, then we will have to update the c++ code. Deleting a key from xml without also updating the c++ code will result in missing keys.

> The thing is that now instead of the vanilla TXT_KEY_GLOBELAYER_RESOURCES tag the TXT_KEY_CONTROL_RESOURCE_ALL tag should be used.

So you want to replace `Bonus Resources` with `Toggle show all resource display`? I don't think those two are interchangeable and I prefer if we keep `Bonus Resources`. 

I think we should be careful with removing txt keys, even if it looks like two keys says more or less the same. If there are two keys, then the text is used in two different places where it's so different that it's possible that some language will need two different translations. Even if it says the very same in English, it's possible that it implies something in the context, which calls for different grammar in some language.

I think it will be best to restore the missing keys rather than trying to mess around in the code to change the key names. That will break consistency with key naming regarding where they are used.

> but the mod continues to read tags from Vanilla first.

Actually it looks like it doesn't read from Vanilla or it would just have used this text from vanilla.

**Comment by MrZorG33** [comment] 2023-11-21 13:12
if you started the game and looked at what these buttons turn on, you would realize that they are the same thing (although the text is different, the essence is the same).

**Closed as completed** 2023-11-21 21:23 UTC
