### ISSUE TITLE
the unit does not match the profession

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#551] opened 2022-02-06 18:10 UTC
when trying to attack an enemy colony, I noticed that I should attack the Royal Dragoon, but they show me a Free colonist.
![image](https://user-images.githubusercontent.com/61798883/152694701-0720e400-5144-4394-9b92-3a2a659ec8fa.png)

hmm .. and where did the British get the Royal Dragoons from? ..
[war.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8010822/war.zip)

**Comment by raystuttgart** [comment] 2022-02-06 18:28
**@MrZorG33** 
Could you please try to put all the Ressources needed for a "Royal Dragoon" in one of your colonies and see if you can equip it yourself with a "Free Colonist"?
(Because normally it should not be allowed to do so, unless I have messed up XML.)

**Comment by raystuttgart** [comment] 2022-02-06 18:34
**Edit:**
I checked **XML** and it shoud be **impossible** for a **Free Colonist** to equip in the Profession **"Royal Dragoon"**.
(At least this is how it is in branch "Yields", maybe this somehow did not make it to "Plains" ...)

```

                <ProfessionNotAllowed>
                    <VoidProfessionType>PROFESSION_ROYAL_DRAGOON</VoidProfessionType>
                    <bIsNotAllowed>1</bIsNotAllowed>
                </ProfessionNotAllowed>
                
```

@MrZorG33 
Please check your XML "UnitInfos.xml" for **UNIT_COLONIST** if you also find that change in there.
Maybe something went wrong when the XML was merged ...

**Comment by MrZorG33** [comment] 2022-02-06 19:38
@raystuttgart for UNIT_COLONIST
![image](https://user-images.githubusercontent.com/61798883/152698208-46751d40-95d0-4f05-b470-7249a36b4f7c.png)

that's who I can equip in my colony.
![image](https://user-images.githubusercontent.com/61798883/152698319-de58ce2f-f41b-4d83-ad67-c580b75553c9.png)

**Comment by raystuttgart** [comment] 2022-02-06 20:16
Then I have no explanation how AI got "Royal Dragoons".
(Because there is also no DLL-Diplo-Event or Python Event that could give them.)

@Nightinggale
Do you have any explanation for this?
Could you check this at some point. 

I do not understand how this should be possible ...
**canHaveProfession()** should return a **false** for **"Free Colonist"** according to **<ProfessionNotAllowed>**
(So it should never be allowed to have Profession "Royal Dragoon".)

**Comment by MrZorG33** [comment] 2022-02-06 20:54
by the way, he also had the Royal Artillery.

**Comment by raystuttgart** [comment] 2022-02-06 21:04
But it was the right Expert and theoretically he could have gotten that one from "European Wars" DLL Diplomacy Event.
(But the European Wars Diplomacy Event should not give "Royal Dragoon". - At least **not** in current XML config I have.)

**Comment by Nightinggale** [comment] 2022-02-06 21:09
I can load the savegame and confirm what we already know from the screenshot. However I can't figure out why and I can't reproduce it, not even with WB.

**Comment by raystuttgart** [comment] 2022-02-06 21:16
@Nightinggale 
I think it might be related to **bForceCheck**.
It returns "true" before **getProfessionsNotAllowed(...)** is even checked.

bool CvUnit::canHaveProfession(ProfessionTypes eProfession, bool bBumpOther, const CvPlot* pPlot, bool bForceCheck)

But I have not yet checked all places in the logic.
Too tired for now.

**Comment by raystuttgart** [comment] 2022-02-06 21:19
**Edit:**
It might happen in here ...
```

ProfessionTypes CvPlayerAI::AI_idealProfessionForUnitAIType(UnitAITypes eUnitAI, CvCity* pCity)
{
	int iBestValue = 0;
	ProfessionTypes eBestProfession = NO_PROFESSION;

	for (int iI = 0; iI < GC.getNumProfessionInfos(); ++iI)
	{
		ProfessionTypes eLoopProfession = (ProfessionTypes)iI;
		CvProfessionInfo& kProfession = GC.getProfessionInfo(eLoopProfession);

		if (!(kProfession.isCitizen() || kProfession.isWorkPlot()))
		{
			//WTP, ray, Settler Professsion - START
			if (GC.getCivilizationInfo(getCivilizationType()).isValidProfession(eLoopProfession))
			{
				//we can only do this, if it is checking for a Unit in a City
				if (eUnitAI == UNITAI_SETTLER && kProfession.canFound() && pCity != NULL)
				{
					//we better check the size of the City
					//I have no idea, what the population check below in else is supposed to do
					if (pCity->getPopulation() > 1)
					{
						iBestValue = MAX_INT;
						eBestProfession = eLoopProfession;
						break; // do not loop through professions anymore, we already found the best Profession for SETTLER_AI
					}
				}
			
				else 
				//WTP, ray, Settler Professsion - END
				{
					CvUnit* pUnit = NULL;
					if (pCity != NULL)
					{
						pUnit = pCity->getPopulationUnitByIndex(0);
					}
					if (pUnit == NULL || pUnit->canHaveProfession(eLoopProfession, true))
					{
						int iValue = AI_professionValue(eLoopProfession, eUnitAI);

						if (iValue > iBestValue)
						{
							iBestValue = iValue;
							eBestProfession = eLoopProfession;
						}
					}
				}
			}
		}
	}
	return eBestProfession;
}

```

**Comment by raystuttgart** [comment] 2022-02-06 21:22
**Edit 2:**
I think if we check for "ProfessionNotAllowed" also in here the problem should be solved.

`
bool CvPlayer::isProfessionValid(ProfessionTypes eProfession, UnitTypes eUnit) const
`

**Comment by Nightinggale** [comment] 2022-02-07 17:59
I have tried testing this with WB and looked around in the code and I haven't found the culprit for this bug yet. I have however found less than optimal code and added #554 as a task I will look into after the next release. Perhaps this bug will fix itself by itself if the code is rewritten to be clean and readable.

**Comment by raystuttgart** [comment] 2022-02-11 16:48
**It should be fixed now** in my last commit in "Yields", which should be merged to "Plains".
It was in fact caused by **missing restrictions** for Royal Professions **in XML** for some Units.

**Comment by raystuttgart** [comment] 2022-07-24 08:24
**@devolution79** 
See above, I had commited a fix for it in "Yields" on Feb 11.
Please merge that fix to "Plains" and then we can close the issue.

Here is the fix I was talking about.
https://github.com/We-the-People-civ4col-mod/Mod/commit/9876e0ad00d10252d6803b36b9cf7d6abfe1c457

**Comment by raystuttgart** [comment] 2022-11-27 13:05
Ok this is now solved.

**Closed by raystuttgart** 2022-11-27 13:05 UTC
