### ISSUE TITLE
Fort / Monastary upgrades

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#358] opened 2020-02-24 15:18 UTC
Dear Developers,

When playing the 2.7.2 Beta 1 version I noticed that when I build a monastery or a fort it does not upgrade after 50 turns when a missionary or a soldier is fortified on the tile. It can be that this feature is removed, however, the pedia says something different. Can anyone please advice if this a deliberate choice or a bug?

Many thanks in advance,

Chris 
The Netherlands

PS - We are all "nagging" about the bugs, but look at it from the bright side: we bloody love your mod so much that we want it to be perfect...! ;-)

**Comment by raystuttgart** [comment] 2020-02-24 17:21
@devolution: 
Wasn't there a bugfix for this?
(I somehow remember that it got broken somehow but was later fixed.)

**Comment by raystuttgart** [comment] 2020-02-24 18:13
ok, I just checked ...
I have no idea what the current status is.

During the time of my retirmenet another modder has heavily modified my original code.
It was somehow merged with "SuperForts" another ModComponent.

**Summary:**
I currently can not tell if "Growing Improvements" for Monasteres and Forts is still working or not ...

**Comment by vissercsp** [comment] 2020-02-24 19:02
...Funny thing... Previously, I waited 8 turns to see if the improvement started, which it did not. After dinner, I restarted my PC, and guess what... It works... Thanks for your help, please close this post.

**Comment by raystuttgart** [comment] 2020-02-24 19:04
By the way, I also found this comment:

**vetiarvind - todo revert**
the complete code line looks like this:
//if ((pPlot->getUpgradeProgress() > 0) || (pPlot->isBeingWorked() && !GC.getImprovementInfo(eImprovement).isUpgradeRequiresFortify())) vetiarvind - todo revert

There are several "todo revert" following ...
There is also an empty "else" block in there ...

Something is really strange.
This code is messed up.

**Comment by raystuttgart** [comment] 2020-02-24 19:06
**@vissercsp** 
Thanks for telling that the code is still working. 
At least we do not need to worry about that.

However the code is really messed up and bad to read.
("Todo" comments, empty "else" code blocks, ...)

So we might at least clean it up a bit.

**Comment by raystuttgart** [comment] 2020-02-24 20:05
**Edit:**
I discovered / experienced something strange.

It seems to be working nicely for **"Forts"**.
But id does **not** seem to be working for **Monasteries** ...

The main difference between these 2 seems to be the following:
Monasteries do not produce their own cultural radius.

**Comment by ErikSandbraaten** [comment] 2020-02-25 06:43
@raystuttgart 
I fixed and refactored a number of issues concerning forts here:
https://github.com/We-the-People-civ4col-mod/Mod/commit/efdb788e9f6dc92e3d536bc06635c62227b13bde

I'm copying the text from a sourceforge ticket concerning forts that I wrote  2018-01-06:

> 
The return value of CvUnit* CvPlot::getFortDefender() (if not null) is a pointer to a defending unit thay may:
1) activate the fort and allow it to grow
2) attack an adjecent enemy

Inside this function is the condition that determines if a unit activates the fort:

    bool isInfantryType = ((pLoopUnit->getUnitClassType() == GC.getDefineINT("UNITCLASS_KING_REINFORCEMENT_LAND") || pLoopUnit->getUnitClassType() == GC.getDefineINT("UNITCLASS_CONTINENTAL_GUARD") 
        || (pLoopUnit->getProfession()!=NO_PROFESSION && GC.getProfessionInfo(pLoopUnit->getProfession()).isCityDefender() && !GC.getProfessionInfo(pLoopUnit->getProfession()).isUnarmed())));
ISSUES:

1) Hard-coded unitclasses
Not a bug, but poor design

2) Obsolete unitclass: UNITCLASS_KING_REINFORCEMENT_LAND
Caused by 1) and currently has no effect since there is no such unit class

3) Lack of gametext that explains how to activate the fort (need to check the pedia if it explains the conditions correctly)
CvGameTextMgr::setImprovementHelp need to be updated (I think this the the correct function)
This will inform the player how to activate the fort and hopefully stop them from complaining :/

4) If a fort is within the workable range of a city, assigning for instance a farmer to work the fort tile will allow the fort to grow, even if there's no valid defender in the fort.
I am pretty sure that this is not intentional, but rather a side-effect of the existing improvement growth system that does not make an exception for the fort.
Note that the monastery may also have this problem.

5) We need to come up with a simpler rule for which units may activate the fort.
Units that cannot get defensive bonuses should not be allowed to activate the fort (what would they gain ?). The same should apply for invisible units like rangers.
The existing code suggests that only infantry can activate the fort. There is no way to check that a unit is infantry, so it could be easier to allow units that can received defensive bonuses to activate the fort (so light artillery is ok).

The condition for activating the fort could be:
noDefensiveBonus == false AND isunarmed == false AND isInvisible == false

The problem with this is that most professions (except the colonist and missionary) is considered armed (isunarmed is false), which is rather strange, thus we cannot easily filter out colonists by checking for unarmed units. I suppose we could commit to changing the XML to make better use of these tags (I think they are not really used for anything), since they would simplify the fort condition.

I'd appreciate some input on this!

**Comment by ErikSandbraaten** [comment] 2020-02-25 06:46
I think I correct all of these except the gametext. I do agree that we could probably do with another round and independent verification. I did test my changes pretty well though, so now forts are at least usable. I don't remember if I did something with monasteries (probably not though)

**Comment by raystuttgart** [comment] 2020-02-25 07:10
Monasteries might be usable as well - meaning that their core functionality (converting and having Natives bring presents) might be working. I simply **do not know** currently.

I noticed though that Monasteries do not grow if not inside City Radius.

**about UNITCLASS_KING_REINFORCEMENT_LAND:**
There is - and it is **not obsolete**.
(Check **GlobalDefinesAlt.xml**)

**about activating the Fort / the Monastery:**
I can still tell you everything about my old design. (Which is pretty much what Pedia says.)
But it was so heavily modified that I do not think it is still all true.

**about forts being in City Radius and having Workers work in it:**
In my old design that was not possible.
It was not allowed to be built in City Radius.
Only the Fortification of an appropriate Unit allowed it to grow.

**Summary:**
I fully agree that this needs to be checked and improved again. (Especially the Monastery part.)
The problem is very simple: 3 modders worked on it and each of them did not fully understand what the previous modder did.
This is not an accusation, it is simply an observation and very understandable.

**Comment by raystuttgart** [comment] 2020-02-25 08:46
@ErikSandbraaten 
I currently suspect that all we need to do is to give Monasteries their **own "1-Plot-Culture-Radius" on its central Plot**.
Then "Growing Improvements" should work for them.
Most likely the Monastery features (converting, calming Native Raiders and convincing to bring presents) will work again as well.

**Comment by raystuttgart** [comment] 2020-02-26 11:27
This is fixed now.
(Monasteries will generate "Culture" on their own plot - just the plot itself.)

I will commit/push my fix to fishes.

**Closed** 2020-02-26 11:30 UTC

**Comment by raystuttgart** [comment] 2020-02-26 11:32
By the way:
The problem was only related to Monasteries outside of Cultural Radius of the Player.
(My fix will just make sure that a Monastery will get Cultural Ownership of a plot if it is not already claimed.)
This will then allow it to grow.
All the code for "Super Forts" and other improvements done were not touched, do not worry.
