### ISSUE TITLE
colony storing negative cargo bug

### ISSUE THREAD

**Issue by GeneralJah215** [We-the-People-civ4col-mod/Mod#494] opened 2021-08-02 04:06 UTC
I received a popup window stating that I had a colony with negative cargo and to report the bug with a save right before it happened.

Hopefully this is what you needed
[Admiral Jah save before negative cargo.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6914330/Admiral.Jah.save.before.negative.cargo.zip)

**Comment by raystuttgart** [comment] 2021-08-02 08:57
Hi GenralJah,

the negative Storage Bug is known already.
But we still could not fully track it down and fix it.

So the savegame is important and may help.

One of the other WTP modders like @Nightinggale or @devolution will probably take a look at it.
They are much better programmers like me and had already started to analyze.

Best regards
ray

**Comment by Nightinggale** [comment] 2021-08-02 14:08
> But we still could not fully track it down and fix it.
To be more specific, negative storage is the result or symptom of a bug, not the cause of it. I fixed a few bugs already, which causes this, but apparently there are even more bugs where code takes from storage without checking if it's a valid action.

Those bugs are mostly old ones. The new part is that I added an error message in order to track down the bugs rather than having AI players secretly mess up due to negative storage.

**Comment by GeneralJah215** [comment] 2021-08-02 15:00
so quick question, is this bug a game breaker?  it seems to pop up every turn on the game I am in with it

**Comment by Nightinggale** [comment] 2021-08-02 15:19
> so quick question, is this bug a game breaker? it seems to pop up every turn on the game I am in with it

Most likely not. Also you can save and load to reset negative values to 0. That will not fix the bug itself, but it will reset the error message. If the message shows up again then it's because the bug itself triggered again, which would be interesting for trying to figure out what is causing this.

**Comment by ErikSandbraaten** [comment] 2021-08-03 11:12
@Nightinggale 

I propose that we implemented some more exhaustive measures for detecting these bugs.

IMO, the primary problem is that we lack context (i.e. no backtrace) when we receive bug reports, therefore I think that we should instrument every call site to CvCity::setYieldStored with a unique id so that we can easier home-in on the culprit (there could very well be several ofc).  We can then present this id in the assert dialog and/or message box.
If we could find a decent backtrace library, that would be even better! Maybe C2C already has this ?

Alternatively we could turn the assertion checks into mandatory checks so that even a release build will check them. I don't think it will cause too much of a performance impact. We still need to log the caller though.

Also note that the MessageBox(...) is causing an AV. It may be that it is inappropriate to attempt to show the messagebox when CvCity::setYieldStored is in the CvGame::Update() callchain.  Amusingly, this doesn't cause a crash (I suspect that it's caught "and smallowed" by the exe somehow), but it does break into the debugger if hosted. 
I propose that we defer the msg box to to when the game is idle / just processing the rendering loop.

**Comment by ErikSandbraaten** [comment] 2021-08-03 11:15
I'd also like to note that this issue seems rather rare in my develop branch. It only triggers in  perhaps somewhere between 500 and 1000 turns in Autoplay so we have likely made some progress.

**Comment by raystuttgart** [comment] 2022-07-24 08:18
This is a duplicate of Issue #501

**Closed by raystuttgart** 2022-07-24 08:18 UTC
Labels: bug
