### ISSUE TITLE
Does the AI know how to utilise fishing / whaling?

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#300] opened 2019-10-05 20:52 UTC
Does the AI know how to fish/whale? Has anybody seen this?

**Comment by NoFreeUsernameDammit** [comment] 2019-10-09 19:18
Seen a few fishing boats working their trade last time I played, but never any whaling boat.

**Comment by ErikSandbraaten** [comment] 2020-01-02 11:43
They do work but they are rarely built be the AI. Usually the AI obtains them from founding fathers I believe. It doesn't help that they tend to be killed off by privateers as well.

**Comment by raystuttgart** [comment] 2020-01-03 11:53
**devolution** is completely right.

AI does know how to handle Fishing Boats and Whaling Boats.
Basically it uses the same logic that is used as for the Human Player when he automates these units.

But it simply puts very little priority to build these units.
That is not necessarily wrong though.

With Whaling Boats it is even worse than for Fishing Boats.
Fishing Boats directly gather Food which is easy to use for AI.
Whaling Boats however gather a raw Yield that only gets valuable if transformed into a Produced Yield by using the appropriate Building and Profession.

This is mostly an issue of balancing of AI value calculations which can easily be done in XML. (Units, Yields, Profession and Buildings)
I would be very careful though to change something here because AI could easily end up neglecting something more important.

**Summary:**
This is not a bug. This might be a minor balancing topic.
But I suggest to leave it as it is for now before unnecessarily messing something up and accidently weaking AI even more.

**Comment by raystuttgart** [comment] 2020-01-27 16:48
Is there still anything to do with this?
Otherwise we could also close it.

**Comment by ErikSandbraaten** [comment] 2020-01-28 06:35
Nope, I'll close it.

**Closed by ErikSandbraaten** 2020-01-28 06:35 UTC
Labels: BUG TO CONFIRM, Discussion, Question
